### ISSUE TITLE
Deeplinking with data source issue

### ISSUE THREAD

**Issue by Symar** [no81no/jplist#100]
Hello,

When i'm using data source with deeplinking currentPage in url adress doesn't work properly.
On page load, currentPage has valid number 0, but when i click in pagination any number for the first time, currentPage still holds 0, and after that when i click on another number in pagination currentPage has value of previous page.

I'm using php-mysql and dataType: html.

**Comment by no81no** [comment]
Could you send me a link to your page so I could see the issue?

**Comment by Symar** [comment]
http://test.kanlux.pl/produkty/13
Login: test
Password: abc123

**Comment by no81no** [comment]
Thank you, I'll check it on weekend and let you know what I found.

**Comment by no81no** [comment]
The issue is fixed.
Please get the latest core file:
https://github.com/no81no/jplist/blob/master/jplist-core/minified/jplist-core.min.js

**Comment by Symar** [comment]
I've overwritten core file and still the same effect.

**Comment by no81no** [comment]
Fixed again, please use last core file and last versions of all controls:
https://github.com/no81no/jplist

**Comment by Symar** [comment]
Awesome. It works!
Thanks a lot.

**Comment by no81no** [comment]
I'm glad it's OK now :)
