### ISSUE TITLE
Possible improvment: add schema.org markup for star-rating

### ISSUE THREAD

**Issue by ksudac** [no81no/jplist#101]
First off, great work and THANK YOU!! I am using the star-rating, however it doesn't follow the schema.org markup https://schema.org/Rating It would be a great addition to the code.

**Comment by no81no** [comment]
Thank you for the great idea, it will be implemented in the future updates.

**Comment by no81no** [comment]
I've check schema.org and found that there are different types of markup depending on the specific content and user preferences (microdata, RDFa etc.). So it will be better to leave it for the user consideration.
