### ISSUE TITLE
Enhancements: Select All Checkboxes, Reset per filter Control & Infinity Scroll

### ISSUE THREAD

**Issue by Extracreative** [no81no/jplist#102]
**Enhancement 1:** 'Select All' checkbox for [Checkbox Path Filter Control](https://jplist.com/controls/checkbox-pa th-filters) & [Button Path Filter Control](https://jplist.com/controls/button-filters#preview)
For example [here](http://www.sanwebe.com/2014/01/how-to-select-all-deselect-checkboxes-jquery)
*I was able to add this but it doesn't trigger the call for "server-json.php" any idea???*

**Enhancement 2:** 'Reset Per Filter - currently reset button clears all. Could have a reset button assign to a filter control, which clears all buttons or checkboxes selected.
*I was able to add this but it doesn't trigger the call for "server-json.php" any idea??*

**Enhancement 3:** ' Infinity Scrolling as an option instead of pagination

**Comment by no81no** [comment]
Thank you for the ideas.

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#6
