### ISSUE TITLE
Is there any way to pre-fill the title-filter or desc-filter?

### ISSUE THREAD

**Issue by mindbodyheart09** [no81no/jplist#105]
For the example of div-layout.html, if "Arch" is pre-filled in title-filter input box, it should display the filtered content until users modify or delete the text "Arch". 

The image below shows what I tried but it doesn't work,

![Image](https://dl.dropboxusercontent.com/u/30587978/tmp.png)

Any help would be appreciated,

Michael

**Comment by no81no** [comment]
You can use a standard input property **value** for this:

```
	<input 
		data-path=".title" 
		type="text" 
		value="arch" 
		placeholder="Filter by Title" 
		data-control-type="textbox" 
		data-control-name="title-filter" 
		data-control-action="filter"
	/>
```	


Thanks,

**Comment by mindbodyheart09** [comment]
thanks,
