### ISSUE TITLE
Is there any way to do a search instead of filter?

### ISSUE THREAD

**Issue by mindbodyheart09** [no81no/jplist#106]
For example, if I enter a word "winter" in both Title filter box and Preview filter box, I'd like to show messages that either have "winter" in title or in preview,

Thanks in advance,

M@

**Comment by no81no** [comment]
Hi,
I'm not sure I understand the need, please send a link to your page.
In general case you may use one textbox with path to the whole item instead of 2 textboxes.
For example,   

```
<input 
	 data-path=".item-content" 
	 type="text" 
	 value="" 
	 placeholder="Filter by Title" 
	 data-control-type="textbox" 
	 data-control-name="title-filter" 
	 data-control-action="filter"
/>
```

Where the item could be:

```
<!-- item -->
<div class="list-item">	
	<div class="item-content">...</div>
</div>
```
