### ISSUE TITLE
Range filter using textboxs or inputs

### ISSUE THREAD

**Issue by pepesenaris** [no81no/jplist#108]
I would like to have/implement a range filter, ie min <= value <= max just like the built in range that depends on jquery-ui slider but using 2 texboxs or inputs..

I don't want to depend on jquery-ui slider and it seems cumbersome to hide a slider and emulate the click events..

Do you have any recomendations on what to modify or add to archive that?

**Comment by no81no** [comment]
Unfortunately there is no out of the box solution for this purpose. You may check the following control:
https://jplist.com/controls/range-toggle-filter#preview
and try to change it for you needs. The source code could be found here:
https://github.com/no81no/jplist/tree/master/jplist-bundles-and-controls/jplist-filter-toggle-bundle/source-code/js/range-slider-toggle-filter

**Comment by pepesenaris** [comment]
Thanks for your response.
I end up using the range slider. Nevertheless i do tried to adapt the range-slider-toggle filter but it was not easy. I changed the  data attribute, where the min(max) value was stored and try to programmatically trigger a filtering but it was unsuccessful. 
As i understand, once you initialize the plugin there's little you could do. because a lot of information is calculated in the init process.

Anyway, thanks for your time.
