### ISSUE TITLE
UI Range Slider - hide and disable first handle

### ISSUE THREAD

**Issue by shabbirrahman** [no81no/jplist#109]
Hi,

I'm using UI Range Slider. I want to hide and disable first handle as for me starting value is fixed. How can I do that?

Thanks,
Shabbir

**Comment by no81no** [comment]
Please check the below example:

```html
<script>
$('document').ready(function(){

	/**
	* user defined functions
	*/
	jQuery.fn.jplist.settings = {
		
		/**
		* LIKES: jquery ui range slider
		*/
		likesSlider: function ($slider, $prev, $next){

			var MIN = 100
				,MAX = 350;
			
			$prev.text(MIN + ' likes');
			
			$slider.slider({
				min: MIN
				,max: MAX
				,range: 'min'
				,value: [MIN]
				,slide: function (event, ui){
					$next.text(ui.value + ' likes');
				}
			});
		}
		
		/**
		* LIKES: jquery ui set values
		*/
		,likesValues: function ($slider, $prev, $next){
			$next.text($slider.slider('value') + ' likes');
		}
	};
				
	/**
	* jPList
	*/
	$('#demo').jplist({
		itemsBox: '.list'
		,itemPath: '.list-item'
		,panelPath: '.jplist-panel'
	});
	
});
</script>
```

```html
<!-- panel -->
<div class="jplist-panel box panel-top">						
						
	<!-- likes range slider -->
	<!-- likesSlider and likesValues are user function defined in jQuery.fn.jplist.settings -->
	<div 
		class="jplist-range-slider"
		data-control-type="range-slider" 
		data-control-name="range-slider-likes" 
		data-control-action="filter"
		data-path=".like"
		data-slider-func="likesSlider" 
		data-setvalues-func="likesValues">
							
		<div class="value" data-type="prev-value"></div>
		<div class="ui-slider" data-type="ui-slider"></div>
		<div class="value" data-type="next-value"></div>
	</div>
	
</div>
```

**Comment by shabbirrahman** [comment]
Before you replied I tried following approach and it worked, but that's to me a dirty way. I haven't tried you're way because we decided not to use slider, instead use Checkbox filter.

//extend jQuery UI slider widget's _mouseCapture function to allow disabling handles
//_mouseCapture function copied from jQuery UI v1.10.3
$.widget("ui.slider", $.ui.slider, {
 _mouseCapture: function (event) {
     var position, normValue, distance, closestHandle, index, allowed, offset, mouseOverHandle,
     that = this,
         o = this.options;

     if (o.disabled) {
         return false;
     }

     this.elementSize = {
         width: this.element.outerWidth(),
         height: this.element.outerHeight()
     };
     this.elementOffset = this.element.offset();

     position = {
         x: event.pageX,
         y: event.pageY
     };
     normValue = this._normValueFromMouse(position);
     distance = this._valueMax() - this._valueMin() + 1;
     this.handles.each(function (i) {
         // Added condition to skip closestHandle test if this handle is disabled.
			// This prevents disabled handles from being moved or selected.
         if (!$(this).hasClass("ui-slider-handle-disabled")) {
             var thisDistance = Math.abs(normValue - that.values(i));
             if ((distance > thisDistance) || (distance === thisDistance && (i === that._lastChangedValue || that.values(i) === o.min))) {
                 distance = thisDistance;
                 closestHandle = $(this);
                 index = i;
             }
         }
     });
     
     // Added check to exit gracefully if, for some reason, all handles are disabled
     if(typeof closestHandle === 'undefined')
         return false;

     allowed = this._start(event, index);
     if (allowed === false) {
         return false;
     }
     this._mouseSliding = true;

     this._handleIndex = index;

     closestHandle.addClass("ui-state-active")
         .focus();

     offset = closestHandle.offset();
     // Added extra condition to check if the handle currently under the mouse cursor is disabled.
		// This ensures that if a disabled handle is clicked, the nearest handle will remain under the mouse cursor while dragged.
     mouseOverHandle = !$(event.target).parents().addBack().is(".ui-slider-handle") || $(event.target).parents().addBack().is(".ui-slider-handle-disabled");
     this._clickOffset = mouseOverHandle ? {
         left: 0,
         top: 0
     } : {
         left: event.pageX - offset.left - (closestHandle.width() / 2),
         top: event.pageY - offset.top - (closestHandle.height() / 2) - (parseInt(closestHandle.css("borderTopWidth"), 10) || 0) - (parseInt(closestHandle.css("borderBottomWidth"), 10) || 0) + (parseInt(closestHandle.css("marginTop"), 10) || 0)
     };

     if (!this.handles.hasClass("ui-state-hover")) {
         this._slide(event, index, normValue);
     }
     this._animateOff = true;
     return true;
 }
});


$('.selector').find(".ui-slider-handle").first().addClass('ui-slider-handle-disabled').hide();

**Comment by no81no** [comment]
Thank you for sharing your code.

**Comment by amitjoshi2188** [comment]
Hello, can you put whole code regarding disable  first slider handler ? 
i tried both of your code
(1) error showing "Cannot set property 'settings' of undefined" 
(2) and in second event cant understand how to code, it shows blank screen.

thanks
