### ISSUE TITLE
Re initaiting the plugin creates a problem

### ISSUE THREAD

**Issue by chknabeel** [no81no/jplist#110]
Hi, I am loading items via my custom script and not using jplist for listing items. I am only using jplist for filtering and pagination. And I call this function when my scripts loads more items:
function init_list_filters (key)
{
	//check all jPList javascript options
   $('#'+key+'_sort').jplist({				
      itemsBox: '.list' 
      ,itemPath: '.list-item' 
      ,panelPath: '.jplist-panel'
	  ,historyLength: 0
	  ,cookiesExpiration: 0
   });
}

Now, the issue is, jplist sorts, filter and paginates correctly on first load but when I load more items and re call init_list_filters() function it somehow remembers the previous values of sorting, filtering and pagination. 
Please tell me how I re-initiate this plugins so previous values don't show up.

Thanks
Nabeel

**Comment by no81no** [comment]
You may add / remove items using jPList API:
https://jplist.com/documentation/js-settings#api
Please let me know if it helps.

**Comment by chknabeel** [comment]
Hi mirium,
Thanks for the fast reply.
I have to recode my script for that. Can we simple re initiate the plugin somehow?

**Comment by no81no** [comment]
Unfortunately there is no simple way to reinitiate it :(

**Comment by chknabeel** [comment]
I see. I really liked the plugin it has all the features I needed. but.. :D
Nice work!

**Comment by no81no** [comment]
Thank you :)
