### ISSUE TITLE
How to set datepicker date

### ISSUE THREAD

**Issue by clod986** [no81no/jplist#111]
Hi, I'm using this https://jplist.com/controls/date-picker-range-filter#usage correctly but I would like it to be set on a specific date. My goal is to show it to the user already filtered.

Thanks

**Comment by clod986** [comment]
I've managed the starting value by doing
<pre>
redrawCallback: function(collection, $dataview, statuses){
                //this code occurs on every jplist action
                $.each($('.jplist-date-picker-range .datepicker'), function(){
                    if($(this).val() == '' && $(this).attr('value')){
                        $(this).val($(this).attr('value'));
                    }
                });
            }
</pre>
How can I force a redraw at this point?

**Comment by no81no** [comment]
Please get the latest version of jquery ui bundle:
https://github.com/no81no/jplist/blob/master/jplist-bundles-and-controls/jplist-jquery-ui-bundle/minified/jplist.jquery-ui-bundle.min.js

You  may set default date in the value of inputs:

```html
<!-- date picker range filter -->
<!-- data-datepicker-func is a user function defined in jQuery.fn.jplist.settings -->
<div
   data-control-type="date-picker-range-filter" 
   data-control-name="date-picker-range-filter" 
   data-control-action="filter"
   data-path=".date" 
   data-datetime-format="{month}/{day}/{year}"
   data-datepicker-func="datepicker"
   class="jplist-date-picker-range">
						
   <input
	  type="text"
	  class="date-picker"
	  value="01/01/2011"
	  placeholder="Datepicker"
	  data-type="prev" />
   
   <span class="gap">-</span>
   
   <input
	  type="text"
	  value="01/01/2015"
	  class="date-picker"								
	  placeholder="Datepicker" 
	  data-type="next"/>
</div>	
```
