### ISSUE TITLE
Range Filter: Select un-select dynamically

### ISSUE THREAD

**Issue by shabbirrahman** [no81no/jplist#112]
Hi,

I have only one range filter 0-100 miles. If there are at least 1 row then I want to keep it selected, but if there are no rows within 0-100 miles then I want to keep it un-selected. How can I do this using javascript, for example I have a javascript variable which indicates whether table has row within 0-100 range or not.

var hasRowWithinRange;

when 
hasRowWithinRange=true  make the filter selected
when 
hasRowWithinRange=false  make the filter un-selected

I've html like this

							  <ul>
						           <li>
						             
						             <span data-control-type="range-filter" data-control-name="miles-range-filter1"  data-control-action="filter" data-path=".map-result-distance"  data-min="0"  data-max="100">
						                  <i class="fa fa-caret-right"></i>
						                  Miles: 0 - 100
						             </span>
						           </li>
						
					         </ul>

Thanks
Shabbir

**Comment by no81no** [comment]
You may try the following code:

```javascript
var $span = $('[data-path=".map-result-distance"]');

if(hasRowWithinRange && !$span.hasClass('.jplist-selected')){

	//make the filter selected
	$span.trigger('click');
}

if(!hasRowWithinRange && $span.hasClass('.jplist-selected')){

	//make the filter un-selected
	$span.trigger('click');
}
```

thanks,
