### ISSUE TITLE
TextBox Filter 1 character bug

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#115]
First thanks for the amazing plugin which is very well documented.

When you typ just 1 character in the TextBox Filter input, the plugin is showing the wrong results. Maybe you can fix this?

Thanks in advance

**Comment by no81no** [comment]
Hi,
I've checked it here:
https://jplist.com/controls/textbox-filter#preview

And it seems to work well. Could you please describe the bug with more details or send me the link to the page with the issue?

Thanks

**Comment by Silvester20** [comment]
Thanks for the reply.

In the link you posted, typ the character "p" by the title-filter, and you will see a wrong result. See the picture.
http://i57.tinypic.com/359g129.png

**Comment by no81no** [comment]
CaPital City has character p in it, so the result is good.

**Comment by Silvester20** [comment]
I thought it will filter by the first character, not the whole word.
Is this possilbe to add this? A filter which filter not the whole word but the first 

So I mean for example

title 1 = "Hello"
title 2 = "Bye"

Typ in the filter 1 char, the character "e", and the result should be zero, because none of those titles starts with a "e".

**Comment by Silvester20** [comment]
I thought it will filter by the first character, not the whole word.
Is this possilbe to add this? A filter which filter not the whole word but the first

So I mean for example

title 1 = "Hello"
title 2 = "Bye"

Typ in the filter 1 char, the character "e", and the result should be zero, because none of those titles starts with a "e".

**Comment by no81no** [comment]
OK, it's a good idea, I'll try to add it in the future updates.

**Comment by Silvester20** [comment]
Thank you very much, for the help, quick reply's and the amazing plugin!

**Comment by no81no** [comment]
Hi,
I've added this functionality as data-mode="startsWith" attribute:
http://localhost:8086/controls/textbox-filter#settings

Please download the latest files:
https://github.com/no81no/jplist/blob/master/jplist-core/minified/jplist.core.min.js
https://github.com/no81no/jplist/blob/master/jplist-bundles-and-controls/jplist-textbox-control/minified/jplist.textbox-filter.min.js

The mode attribute was also added to other text filter controls.
Also other modes available: endsWith, startsWith, advanced, contains (the default option)

**Comment by Silvester20** [comment]
You are awesome mate, it is working fine, thank you very much!

**Comment by no81no** [comment]
You're welcome :)
