### ISSUE TITLE
Textbox filter - <input type="number"> suggestion

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#116]
The TextBoxFilter plugin is using the JS event "keyup". But this event is not triggerd when you use the HTML5 input type is number element, using the integrated arrows of the input.

So after changing the event to "input", it seems to work fine.

So maybe you can add this in the next version?

Change to be made in  "jplist.textbox-filter.min.js" file:
from: $control.attr("data-event-name")||"keyup"
to: $control.attr("data-event-name")||"input"

Thanks in advance

**Comment by no81no** [comment]
You can use any event type using data-event-name attribute like described here:
https://jplist.com/controls/textbox-filter#settings

Thanks,

**Comment by Silvester20** [comment]
Awesome, thanks!
