### ISSUE TITLE
History Back jquery clone() bug

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#118]
Hi,
When you clone a complete page using the jquery function clone(true, true), then remove the page using $remove() and then appending the page back using $append(), the history back button will fail. It doesn't find the previous page anymore.

Not a big deal because instead of removing the page, I can $hide() it, but just want to report it.

Thanks for the very nice plugin!

**Comment by no81no** [comment]
Thank you for reporting this, I'll check it.

**Comment by no81no** [comment]
Hi,
Please try using the following code instead of **clone**:
```javascript
$('document').ready(function(){

	var $demo = $('#demo');
	
	$demo.jplist({				
		itemsBox: '.list' 
		,itemPath: '.list-item' 
		,panelPath: '.jplist-panel'	
	});
	
	//please use detach instead of remove
	$demo.detach();

    //.. other code ...
	
	//append it back when you need
	$('#placeholder').append($demo);			
	
});
```

Please let me know if it helps.

**Comment by Silvester20** [comment]
Awesome, that works smoothly, again thank you so much!

**Comment by no81no** [comment]
You're welcome :)
