### ISSUE TITLE
[Small Issue] Odd/Even classes for items

### ISSUE THREAD

**Issue by awl19** [no81no/jplist#119]
I know this isn't supported by the current plugin, but basically I've got the items styled row by row, even and odd. I'm loading 2 classes, 1 that is added to "odd" rows and 1 that is added to "even" rows. Problem is that when sorted by jPList the styles get mixed up (obviously), so I'm wondering if there's a way to change the jPList code to add/delete/change classes depending out how they're being sorted (based on every other item).

This is just an attempt to differentiate the rows because I'm dealing with lots of results - this is a practical request, not just an aesthetic one.

Thanks in advance! (whether possible or not)

**Comment by no81no** [comment]
This is possible with **redrawCallback**.
Please check the following demo:
https://jplist.com/layoutexamples/table-2

```javascript
$('#demo').jplist({

	itemsBox: '.demo-tbl tbody'
	, itemPath: '.tbl-item'
	, panelPath: '.jplist-panel'

	, redrawCallback: function () {
		$('.tbl-item').each(function (index, el) {
			if (index % 2 === 0) {
				$(el).addClass('even');
			}
			else {
				$(el).addClass('odd');
			}
		});
	}
});
```

**Comment by awl19** [comment]
Thanks for your help, again! Such quick responses too!

**Comment by no81no** [comment]
You're welcome :)
