### ISSUE TITLE
KeyUp/KeyPress Delay on Text Filter boxes

### ISSUE THREAD

**Issue by LotusJeff** [no81no/jplist#120]
I use jplist with AJAX with PHP and MySql calls. Is there a way to add a KeyUp/KeyPress Delay when a user types a word to be searched?

**Comment by no81no** [comment]
Unfortunately this is not supported for now. 

But it's possible to use button instead of KeyUp/KeyPress event:
https://jplist.com/controls/textbox-filter#usage

The other option is to use **Input** event using **data-event-name** attribute:
https://jplist.com/controls/textbox-filter#settings

**Comment by ktatsache** [comment]
Hi,

do you have now a solution for that? I didn't found one in the documentation.

Thanks
