### ISSUE TITLE
[Suggestion] - Add range as setting (Pagination)

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#125]
Hi there, just want to ask if you could create an setting of the 'range'-option of the file 'jplist.pagination-bundle.min.js'.

    jQuery.fn.jplist.controlTypes.pagination = {
        className: "Pagination",
        options: {
            range: 7, /** here **/
            jumpToStart: !1,

Just like this

    jplist
    ({
	     itemsBox: '.list' 
        ,range: 7
    });

**Comment by no81no** [comment]
Hi,
You have data-range attribute in html:
https://jplist.com/controls/pagination#settings

Thanks,

**Comment by Silvester20** [comment]
Didn't noticed, but that is indeed what I want, so thanks!

**Comment by no81no** [comment]
You're welcome :)
