### ISSUE TITLE
 Deeplinking with daterange filter only restores / sets one value

### ISSUE THREAD

**Issue by akiessling** [no81no/jplist#126]
Hi,
If prev and next are set in the url from a daterange filter, only the prev value will be restored. If only one value is set (either prev or next), that one will be restored correctly.

Example:
2-jquery-ui-date-picker-range-filter-demo.html#date-picker-range-filter:prev=2015~7~2|date-picker-range-filter:next=2015~7~27 (with deepLinking: true) only sets 08/02/2015

**Comment by no81no** [comment]
The issue is fixed, please download the latest js file:
https://github.com/no81no/jplist/blob/master/jplist-bundles-and-controls/jplist-jquery-ui-bundle/minified/jplist.jquery-ui-bundle.min.js
