### ISSUE TITLE
Numbers with decimals not sorting properly

### ISSUE THREAD

**Issue by awl19** [no81no/jplist#127]
Hey, again! =D

I'm using jPList for a project TONS of tables worth of numbers. All of them sort correctly except when I get a column of numbers with decimals, then it...kind of works. Most of the numbers will sort, but then  it takes like 10% of the numbers and puts them into random rows.

Is there a solution for this already that I'm not aware of? I scoured through the documentation for something, but couldn't find anything.

One other question. I have this weird issue where when I change pages the column I sorted by gets reset. Whether I go forward or back a page.

```<script>
    $('document').ready(function (event) {
        var $jplist = $('#jplist');
        $jplist.jplist({
            itemsBox: '.table tbody'
            , itemPath: 'tr'
            , panelPath: '.jplist-panel'
            , storage: 'localstorage'
            , storageName: 'gridiron-stats-QB'
            , effect: 'fade'
            , redrawCallback: function () {
                $('#jplist tr').each(function (index, el) {
                    if (index % 2 === 0) {
                        if ($(el).hasClass('even')) {
                        } else {
                            $(el).addClass('even');
                        }
                        if ($(el).hasClass('odd')) {
                            $(el).removeClass('odd');
                        }
                    } else {
                        if ($(el).hasClass('even')) {
                            $(el).removeClass('even');
                        }
                        if ($(el).hasClass('odd')) {
                        } else {
                            $(el).addClass('odd');
                        }
                    }
                });
            }
        });
    });
</script>
```

Any help would be greatly appreciate.

Thanks!

**Comment by no81no** [comment]
Hi,
I checked numbers with decimals and it seems to work OK. Please send me html, the link to the demo page or link to jsfiddle so I could see the issue. The same about the second problem.

**Comment by awl19** [comment]
Thanks for your response =)

Days after I posted this the number issue resolved itself and I haven't seen it since, but the the page problem with sorting still exists.

You can see it in action here: http://ethicalchamphosting.com/ffstats/

**Comment by no81no** [comment]
I'm glad that is works now :)
Please close this issue if it's resolved.

**Comment by awl19** [comment]
Hey, thanks again for your response.

Maybe I should have been more clear. The decimal issue is resolved, but the sorting issue is not. It's a pretty big flaw that I still can't figure out.

**Comment by no81no** [comment]
Maybe you can use jplist sort dropdown controls in the table headers instead of custom script. There is an example with sort buttons in table headers: http://jplist.com/layoutexamples/table-with-sortable-columns. Sort buttons can be replaced with sort dropdown / select controls.
