### ISSUE TITLE
Deeplink not working for pagination control.

### ISSUE THREAD

**Issue by micahlisonbee** [no81no/jplist#129]
The deeplink URL is modified correctly when I apply filters, however when I change the page the URL does not change to reflect the changes:

Live URL: https://foundermusic.com/tracks

Sample HTML:

    <div 
    class="jplist-pagination mobile-margin" 
    data-control-type="pagination" 
    data-control-name="paging" 
    data-control-action="paging"
    data-control-animate-to-top="true"
    data-items-per-page="25"
    data-range="5"
    data-mode="google-like">
</div>

**Comment by no81no** [comment]
What is the access code to your demo page?

**Comment by micahlisonbee** [comment]
Sorry about that, it's: FounderBeta

Micah

**Comment by no81no** [comment]
no problem :)

**Comment by micahlisonbee** [comment]
Any diagnostics on this?

**Comment by no81no** [comment]
I still need a link to your issue :)
I can't reproduce it locally, all seems to be fine.

**Comment by micahlisonbee** [comment]
https://foundermusic.com/tracks
Beta Code: FounderBeta

**Comment by no81no** [comment]
I selected "acoustic" and the following URL works OK:
https://foundermusic.com/tracks#genre:textGroup=acoustic|track-row-filters:selected=.is-staff-pick!text!asc|paging:number=25

Please describe the scenario that doesn't work

**Comment by micahlisonbee** [comment]
Yes that is working correctly. Try changing the page at the bottom. The URL does not change when you change pages.

**Comment by no81no** [comment]
OK, I see it now. 
I'll check it and let you know once it resolved.

**Comment by micahlisonbee** [comment]
Any progress on this? Let me know if you need any help.

**Comment by no81no** [comment]
The issue is fixed, please download the latest pagination js.

**Comment by micahlisonbee** [comment]
Looks good, thanks!
