### ISSUE TITLE
Lazy loading images on page 2 and beyond not showing images

### ISSUE THREAD

**Issue by QuillDesign** [no81no/jplist#130]
We're using basic lazy load scripts and when we load up the first page everything is fine - but if using any of the filters the images stop lazy loading and don't load images at all.

You can view the development site at 
http://qd.kings1912.com/jewelry-119897.cfm

Select a filter and you'll see the issue (Images just "loading...")

**Comment by QuillDesign** [comment]
All the other information is showing and sometimes if I minimize the browser and then max again it will load the images ... its very odd.

**Comment by no81no** [comment]
Please use 'Redraw Callback' Function:

```
<script type="text/javascript">   
   $('document').ready(function(){

      $('#demo').jplist({

         //main options
         itemsBox: '.list' //items container jQuery path
         ,itemPath: '.list-item' //jQuery path to the item within the items container
         ,panelPath: '.panel' //panel jQuery path
 
         ,redrawCallback: function(collection, $dataview, statuses){
           
            //your lazyload script should be heere
            $('.lazy').lazyload();
         }                       
      });
   });
</script>
```

**Comment by QuillDesign** [comment]
Still no dice

$('document').ready(function () {
		    $('.products').jplist({

		        itemsBox: '.ul-li-list'
				, itemPath: '.list-item'
				, panelPath: '.jplist-panel'

		        //save plugin state
				, storage: 'localstorage' //'', 'cookies', 'localstorage'			
				, storageName: 'jplist-ul-li'
				
				,redrawCallback: function(collection, $dataview, statuses){

		            //your lazyload script should be heere
		            $("img.lazy").lazyload();
		         }  

				
		    });
		
		
		});

**Comment by QuillDesign** [comment]
I am finding that the redraw function is "not" being called everytime an action is fired - it's called after the first but then not again.

**Comment by QuillDesign** [comment]
Nevermind - it is being called everytime.

**Comment by QuillDesign** [comment]
I am using the $("body,html").scroll() to trigger the scroll event and it works the first filter selection but not 2nd or beyond.  Just don't know what to do.

Here is my code:

<script>
		$('document').ready(function () {
		    $('.products').jplist({
		        itemsBox: '.ul-li-list'
			, itemPath: '.list-item'
			, panelPath: '.jplist-panel'
			,redrawCallback: function(collection, $dataview, statuses){
				console.log('redraw');
	            		//your lazyload script should be heere
	           	 	$("img.lazy").show().lazyload();
				$( "body,html" ).scroll();	
		         }  
		    });
		});
	</script>

**Comment by QuillDesign** [comment]
$('document').ready(function () {
		    $('.products').jplist({
		        itemsBox: '.ul-li-list'
			, itemPath: '.list-item'
			, panelPath: '.jplist-panel'
			,redrawCallback: function(collection, $dataview, statuses){
				console.log('redraw');
	            		//your lazyload script should be heere
	           	 	$("img.lazy").show().lazyload();
				$( "body,html" ).scroll();	
		         }  
		    });
		});

**Comment by no81no** [comment]
For scroll to top you may use the following setting:
"animateToTop: 'html, body'"
Please check the full list of settings here:
https://jplist.com/documentation/js-settings
