### ISSUE TITLE
Open a page on a specific item

### ISSUE THREAD

**Issue by jurzyna** [no81no/jplist#131]
I am implementing a search results page for my site. The site contains multiple jplists. I want to create a link for the searched item that will take me to a jplist with the file opened on the page with the right pagination number selected.

Is this possible? I am adding a unique Id to every item.

**Comment by no81no** [comment]
Please use deep links:
https://jplist.com/documentation/js-settings#deep-links

**Comment by jurzyna** [comment]
Thank you for answering :)

I use deep links already, the only way I can achieve what I want for now is to display all the items on my page with deeplinks and than jump to the item with the location.search I added manually to the URL:
http://local.intranet.ihf.com:9999/virtual_folders/index/8?file=10#paging:number=all|paging:currentPage=0

But is there a way to do it without showing all items at once. I would like to find out were the file is located within pagination.

Search results page (i don't know where the file is located within the list):
https://www.evernote.com/l/ANpAiD5XUHRE0YxUdz2Ht6tZALTGGlJ0OnU
Item list page:
https://www.evernote.com/l/ANr8OEpo8d9CFLDM-Tzz6zssVUxMHZdOuOg

**Comment by no81no** [comment]
There is no out of the box way to find out item location in pagination now, but you may consider to filter out the items list once the page is loaded. This way the user will see only  the selected item.. This can be achieved using appropriate deep link url.
