### ISSUE TITLE
requirejs

### ISSUE THREAD

**Issue by v2pwww** [no81no/jplist#133]
Is it possible use plugin with amd loader require.js? 
Plugin core imported with require.js shim option like so:
```
shim: {
        'plugins/jplist.core': {
            deps: ['jquery'],
            exports: '$.fn.jplist'
        }
}
```
but have a problem with imported jplist addon. In exaple how to imported filter toggler?

**Comment by no81no** [comment]
Added jplist + require.js demo:
https://github.com/no81no/jplist/tree/master/demo/jplist-with-requirejs-demo
