### ISSUE TITLE
Deeplinking loading all pages and no filters

### ISSUE THREAD

**Issue by QuillDesign** [no81no/jplist#134]
I have deepLinking set to true and when I use the following link:

http://www.kings1912.com/jewelry-119897.cfm?brand=.a-link&pagingNum=12#paging:number=12|paging:currentPage=0

it loads the page - but loads ALL the products and no pagination and no filters (they are blank).

IF i refresh the page it shows just fine ... but the initial load is always messed up (if it's a new link to me and not already visited).

**Comment by no81no** [comment]
The link you provided has wrong structure, and I see the following errors in the firefox console:

![screenshot](https://cloud.githubusercontent.com/assets/947385/10049880/3e650fc8-6222-11e5-8d92-e9b5505730b0.PNG)

http://www.kings1912.com/skins/quill/kings/assets/js/jplist/website.min.js can be removed, I use it for the demo pages only.

The following error causes the issue: 
Error: Syntax error, unrecognized expression: a[href=#paging:number=12|paging:currentPage=0]
I guess it because of wrong URL...

**Comment by QuillDesign** [comment]
what do you mean wrong structure?

**Comment by no81no** [comment]
In general, "brand=.a-link" should be after # and not before it. Is this link generated by the plugin?

**Comment by QuillDesign** [comment]
Yes this link is generated by the plugin … I have removed it as it was
causing problems … but I can put it back.



*From:* Miriam Zusin [mailto:notifications@github.com]
*Sent:* Wednesday, September 23, 2015 11:22 AM
*To:* no81no/jplist
*Cc:* QuillDesign
*Subject:* Re: [jplist] Deeplinking loading all pages and no filters (#134)



In general, "brand=.a-link" should be after # and not before it. Is this
link generated by the plugin?

—
Reply to this email directly or view it on GitHub
<https://github.com/no81no/jplist/issues/134#issuecomment-142653101>.

**Comment by no81no** [comment]
Please return it so I could see the issue.

**Comment by QuillDesign** [comment]
Ok … here is a link generated by filtering by price on the page:



http://www.kings1912.com/jewelry-119897.cfm#price-checkbox-dropdown:pathGroup=.500-1000|paging:number=12|paging:currentPage=0





*From:* Miriam Zusin [mailto:notifications@github.com]
*Sent:* Wednesday, September 23, 2015 1:26 PM
*To:* no81no/jplist
*Cc:* QuillDesign
*Subject:* Re: [jplist] Deeplinking loading all pages and no filters (#134)



Please return it so I could see the issue.

—
Reply to this email directly or view it on GitHub
<https://github.com/no81no/jplist/issues/134#issuecomment-142688883>.

**Comment by no81no** [comment]
As much as I can see the issue is created by some other script. 
To verify this you can comment out jplist call and check if the error still appears in console.

**Comment by QuillDesign** [comment]
Ok I Will take a look and see … thank you.



P





*From:* Miriam Zusin [mailto:notifications@github.com]
*Sent:* Wednesday, September 23, 2015 2:14 PM
*To:* no81no/jplist
*Cc:* QuillDesign
*Subject:* Re: [jplist] Deeplinking loading all pages and no filters (#134)



As much as I can see the issue is created by some other script.
To verify this you can comment out jplist call and check if the error still
appears in console.

—
Reply to this email directly or view it on GitHub
<https://github.com/no81no/jplist/issues/134#issuecomment-142701410>.

**Comment by no81no** [comment]
You're welcome
