### ISSUE TITLE
Not rendering to list

### ISSUE THREAD

**Issue by vosco88** [no81no/jplist#136]
Hi,

I am trying to implement jplist for a site I am working on. So far I have no luck rendering the json data.

Here is a code of the script, I am using Handlebars, and the code is almost the same as in your demos.
The differences are that I use precompiled Handlebar template and GET instead of post.
The success function is there for check for now - I can output the Handlebar template to console just fine but it is not rendering to page.

Can you see where the problem might be?

My code for the script is here:

			$('document').ready(function () {

				var $list = $('#demo .list')
					, template = Handlebars.templates['template'];

				//init jplist with php + mysql data source, json and Mustache template
				$('#demo').jplist({
                                        debug: true
					, itemsBox: '.list'
					, itemPath: '.list-item'
					, panelPath: '.jplist-panel'
                                         
					//data source
					, dataSource: {

						type: 'server'
						, server: {

							//ajax settings
							ajax: {
								url: 'json'
								, dataType: 'json'
								, type: 'GET'
                                                                , success: function(data) {
                                                                    console.log(template(data));
                                                                },
							}
						}

						//render function for json + templates like Mustache, xml + xslt etc.
						, render: function (dataItem, statuses) {
							$list.html(template(dataItem.content));
						}
				}

				});
                                        

			});

**Comment by no81no** [comment]
Please send me the link to your page so I could see the issue.

**Comment by vosco88** [comment]
I've already solved it, forgot to update the ticket.

the issue was that the json was not exactly as in the format needed by the
plugin.

thanks for the response it is a great plugin, very helpful for what I
wanted to do

**Comment by no81no** [comment]
I'm glad that it works for you now.
