### ISSUE TITLE
generate thead with jpanel sorting asc/descding buttons conflicts with jplist item

### ISSUE THREAD

**Issue by JeanVanDenderFlume** [no81no/jplist#137]
How to achieve sort buttons in the thead of a table? I was not able to achieve this because whenever jplist item is used for table generation and row itteration a jpanel control cannot be placed/used.  How to achieve the sorting in the kolomhead, something similair as this http://www.datatables.net/

**Comment by no81no** [comment]
Added demo page with the table with sortable columns:
http://jplist.com/layoutexamples/table-with-sortable-columns

**Comment by JeanVanDenderFlume** [comment]
tank you. I like jplis but i switched to datatables.net because of the
columns. Could not make this work.

Also the controls at the top. Could i place this outside the jplist div  so
that this could move to an other location for responsive layout workings?

2015-11-02 9:16 GMT+01:00 Miriam Zusin <notifications@github.com>:

**Comment by no81no** [comment]
It's possible to do something like this:

//jplist works with the whole page instead of "#demo"
$('body').jplist({
	itemsBox: '.list'
	,itemPath: '.list-item'
	,panelPath: '.jplist-panel' //there are many <div class="jplist-panel">...controls are here ... </div> on the page
});

This way it's possible to use many locations for controls.
