### ISSUE TITLE
Follow-up on "Filter" box. Old problem solved, new problem emerged

### ISSUE THREAD

**Issue by mindbodyheart09** [no81no/jplist#138]
Greetings, I asked a question a while ago : https://github.com/no81no/jplist/issues/106
#
For example, if I enter a word "winter" in both Title filter box and Preview filter box, I'd like to show messages that either have "winter" in title or in preview,
#

The answer has perfectly solved it. For that. I thank,

However, I have found that it creates one problem: the "Reset" button doesn't work on the "Filter" input box,

Any help would be appreciated,

Michael

**Comment by no81no** [comment]
I've checked it and it seems to work well. So please send a link to your page or create a sample with your data on jsfiddle
