### ISSUE TITLE
Possibilty to search whole table using only one search box?

### ISSUE THREAD

**Issue by adrian-f91** [no81no/jplist#139]
Hi, 

Thank you for JPList. The plugin is great!! It's really straightforward to implement into any design and framework.

Currently I have separate search bars to filter the table (as in the demo). 
<img width="396" alt="two search bars" src="https://cloud.githubusercontent.com/assets/9639585/10368583/ecbb53f0-6dcd-11e5-894a-7091c224a07b.png">

I was wondering in there is a way to create a single search filter (one search bar)  that will be able to search the content of the whole table. 
<img width="400" alt="filter by all" src="https://cloud.githubusercontent.com/assets/9639585/10368653/3f0ced44-6dce-11e5-89da-a6db7ae31b44.png">

Thanks.

**Comment by no81no** [comment]
You may use more general data-path attribute to filter the whole table, for example data-path="td".

**Comment by adrian-f91** [comment]
That worked. Thanks a bunch!

**Comment by no81no** [comment]
You're welcome :)
