### ISSUE TITLE
counter control - php-mysql-data-source

### ISSUE THREAD

**Issue by Kapottejas** [no81no/jplist#142]
Hello no81no,

First of all JPLIST is great! 

I have a question, is the counter-control working with the php-mysql-data-source package? I tried to add the js file and the example code, but I don't get numbers between the ()

If it is not included in the php-mysql-data-source, can u add it in the future (read: this year :+1: )?

Or is there an easy way to echo columns count, for example: Architecture (5), Architecture got 5 results after filtering.

(php / jquery snippet)

Thanks!

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#10
