### ISSUE TITLE
Prev Page Button always show

### ISSUE THREAD

**Issue by veralexa** [no81no/jplist#145]
Hi
I want that the jplist-pagingprev (first, jplist-prev) and jplist-pagingnext (jplist-next, jplist-last) always show dont hide. 
I wont show them but disabled if they are not active.

How can i do this. 

Thanks

**Comment by no81no** [comment]
You can edit CSS and add something like this:
.jplist-pagingprev.jplist-hidden,
.jplist-pagingnext.jplist-hidden{
   display: block;
}

**Comment by veralexa** [comment]
Thank you very much thats what i want.

**Comment by no81no** [comment]
You're welcome :)

**Comment by veralexa** [comment]
thank you very much

😊



2015-11-02 13:42 GMT+01:00 Miriam Zusin <notifications@github.com>:
