### ISSUE TITLE
How to PHP and SQL Server Data Source

### ISSUE THREAD

**Issue by userkak** [no81no/jplist#146]

**Comment by no81no** [comment]
Unfortunately this is not supported out of the box. But you can take as example and reference PHP + MySQL version.

**Comment by jamesdelpriore** [comment]
That's what I have been trying to do but have been unsuccessful. Can you think of maybe a easier way for me to accomplish this? All i need is some buttons or even link text that would trigger the query.

The checkboxes work great and I have those all setup but for some reason I cannot get the radio buttons to work.

Thanks
