### ISSUE TITLE
Default sorting reverses the order

### ISSUE THREAD

**Issue by jurzyna** [no81no/jplist#148]
When I leave the sorting in default order the list is being reversed I also checked it and the same happens on the sorting demo page. Is there a way top keep the default order of the list untouched when set to to default?

**Comment by no81no** [comment]
What browser do you use?

**Comment by jurzyna** [comment]
I tested this with Safari, Chrome and Firefox ( 1-sort-select-control.html ).
![screen shot 2015-11-09 at 11 01 50](https://cloud.githubusercontent.com/assets/2195072/11030903/4e4bbb8e-86d1-11e5-9155-511b3fb01e9e.png)

**Comment by no81no** [comment]
OK, I'll check this, thank you for reporting.

**Comment by tiberiur** [comment]
+ 1 here

**Comment by bartolije** [comment]
Same probleme here

**Comment by zzseba78** [comment]
Same problem here, how we can fix it? Thanks

**Comment by rcolpo** [comment]
Any solution on this?

**Comment by zzseba78** [comment]
Seems that don´t fix this yet... jpList seems like a great plugin, but i already declined to use it on a project because this error makes it totally useless

**Comment by Android63** [comment]
Same problem here

**Comment by cayba** [comment]
Any Solution??

**Comment by no81no** [comment]
Fixed 
Can be checked with the following test page:
https://github.com/no81no/jplist/blob/master/demo/7-no-sort-test-page.html
