### ISSUE TITLE
Can we stop refreshing in some cases?

### ISSUE THREAD

**Issue by pannalal** [no81no/jplist#149]
jplist is absolutely superb.

When I use textbox filter, every time I enter a character, it keeps refreshing (php + mysql ajax). This is not a problem in general. However, when you have a table with large number of rows (say 1 million), the performance gets degraded. In such case, is there any way to tell jplist that referesh only if there are minimum three (or 4 or any number of) characters. 

Panna Lal Patodia,
Email: pannalal@usa.net

**Comment by dark46** [comment]
I have so:

Search form:
```html
 <div class="text-filter-box">
    <!--[if lt IE 10]>
    <div class="jplist-label">Search by title:</div>
    <![endif]-->

    <input
       data-path=".title"
       data-button="#title-search-button"
       type="text" value=""
       id="text-search"
       placeholder="Search by title"
       data-control-type="textbox"
       data-control-name="text-filter"
       data-control-action="filter" />
    <button type="button" id="title-search-button">
        <i class="fa fa-search"></i>
    </button>
</div>
```

js:
```javascript
function input_search() {
    $('#title-search-button').click();
}

$('#text-search').keypress(function (e) {
    if (e.which == 13) { // Enter key
        $('#title-search-button').click();
        return false;
    }

    if(this.value.length >= 3) { // auto submit search
        if (input_search.timeout) clearTimeout(input_search.timeout);
        input_search.timeout=setTimeout(input_search,700);
    }
});
```

Enjoy ;)

**Comment by pannalal** [comment]
Many thanks for fast response. It is working perfectly.

**Comment by pannalal** [comment]
Many thanks for your comments. It is still refreshing after each key press.

**Comment by PJanisio** [comment]
I agree to @pannalal but I would like to see refreshing content after defined miliseconds of no input from user side.

In my example - for mdeium size database it consumes some seconds to load content and in this time user can type many letter - but they will not be stored between the refreshing (preloading).

**Comment by no81no** [comment]
It's possible to use "input" event instead of keyup:

`   <input 
     data-event-name="input"
     data-path=".title" 
     type="text" 
     value="" 
     placeholder="Filter by Title" 
     data-control-type="textbox" 
     data-control-name="title-filter" 
     data-control-action="filter"
   />`

You can read more about input event here:
https://developer.mozilla.org/en-US/docs/Web/API/InputEvent

**Comment by PJanisio** [comment]
I have tried already input event. But still it preloads for every letter and if you are typing fast - then it will not work properly.

**Comment by no81no** [comment]
The possible workaround is:

In HTML you declared some custom event (name can be anything):

`<input data-event-name="custom-tb-event" data-path=".title" type="text" value="" placeholder="Filter by Title" data-control-type="textbox" data-control-name="title-filter" data-control-action="filter" />`


In JS after jPList call:
```            
            //data filter be filtered after 500 ms
            $('#title-tb-filter').on('keyup', function(){
                
                setTimeout(function(){
                    $('#title-tb-filter').trigger('custom-tb-event');
                }, 500);
                
            });`

**Comment by PJanisio** [comment]
Thank you! Works great (as always).

Complete html part (with input id):

`<input id="title-tb-filter" data-event-name="custom-tb-event" data-path=".title" type="text" value="" placeholder="Filter by Title" data-control-type="textbox" data-control-name="title-filter" data-control-action="filter" />`

**Comment by no81no** [comment]
I'm glad that it helps.
Also demo page is available here:
https://github.com/no81no/jplist-php-mysql/blob/master/6-textbox-filter-delay.html

**Comment by no81no** [comment]
Please close the issue if it's resolved.
