### ISSUE TITLE
Jquery-ui range-silder does not work on bottom pannel

### ISSUE THREAD

**Issue by danieldiehl** [no81no/jplist#151]
I'm trying to have the filter panels both on top and bottom. For the dropdown and pagination controls it works perfect, does not matter if you change in the panel in the top os bottom, both work.

But for the range slider it does not work. The top one works, but the bottom one does not. 
Looking at the Ajax calls, it does two calls, one for each range-slider. since the top ones is the last call its values prevails. 

Ca you please check and provide an example on have the top panel duplicated in the bottom with a range-slider filter?

Thanks,

**Comment by no81no** [comment]
Demo page:
https://github.com/no81no/jplist/blob/master/demo/5-jquery-ui-range-slider-demo-panels.html
