### ISSUE TITLE
Apply a select filter via jQuery or Javascript

### ISSUE THREAD

**Issue by JimJames23** [no81no/jplist#153]
Hi ! 

First, thanks for your awesome job, it's an amazing plugin !

I have a bunch of filters on top of my table, which works well.
My question is : is it possible to apply a filter via jQuery of Javascript (and in my case it's a select filter) ? And of course make it refreshes the list.

For example this is my select filter :
<code>
< select id="domain-select" class="jplist-select" data-control-type="select" data-control-name="domain-filter" data-control-action="filter">
    
     < option data-path="default" value="">Domain Filter</option>
     < option data-path=".domain1" value="1">Domain 1</option>
     < option data-path=".domain2" value="2">Domain 2</option>
     < option data-path=".domain3" value="3">Domain 3</option>
      
< /select>
</code>
Below is the jQuery used to select the option :
<code>
$("#domain-select > option[value='2']").prop('selected', true);
</code>

This code works "well", it selects the option but of course nothing happens to the list. How can I trigger a refresh ?

Thank you for your response.

Edit : I'm sorry I don't understand why the code is not well indented

JL

**Comment by no81no** [comment]
I guess the missing part here is:
`$("#domain-select").trigger('change');`

**Comment by baras** [comment]
if `$("#domain-select").trigger('change');` doesn't work, try 
```js
var sortBySelect = document.querySelector("#domain-select"); 
sortBySelect.value = "new value"; 
sortBySelect.dispatchEvent(new Event("change"));
```
