### ISSUE TITLE
[Suggestion - Pagination] - Add "data-control-animate-to-top" for mobile only

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#154]
Hi, it's me again.

I am still using this awesome plugin, and got a new suggestion for the pagination again.

Is it possible to animate to top when the user is ONLY using a small screen (like a mobile phone)?
So in example, when the max screen resolution is 320x480, then it should scroll (animate) to top otherwise don't scroll to top.

Cheers!

**Comment by Silvester20** [comment]
Any reply to this?

Btw: Just saw the update "textbox-filter-search-any-text.html demo". This is exactly what I need right now, awesome!

**Comment by no81no** [comment]
You can try the following:
1. disable animate to top feature in jplist settings
2. Use redraw-callback-function http://jplist.com/documentation/js-settings#redraw-callback-function
3. Write the following code in it:
- detect if it's a mobile device (for example, using this script: https://davidwalsh.name/detect-iphone)
- if true -> jump to top

`$('html, body').animate({
			scrollTop: 0
}, 500);`

**Comment by Silvester20** [comment]
Hope this will be an jpList feature in the future but for now I am gonna use the redraw-callback like you said, thanks again!
