### ISSUE TITLE
Keep filter status

### ISSUE THREAD

**Issue by vosco88** [no81no/jplist#160]
Hi,
I am using your plugin on one page.
Basically I have a list of items (doing filters,pagination, etc.) and I've got couple of modals with forms to update and create items. When I hit the button on modal, the controller will do the work and will redirect back to the page it came from.
The problem is after a redirect the jplist filters are not there. 
Could you help me understanding how could I achieve that the page will reload with the same filters as it was when I left it?

Thank you

**Comment by no81no** [comment]
You can keep plugin state using local storage, cookies or deep links:
http://jplist.com/documentation/js-settings#storage
http://jplist.com/documentation/js-settings#deep-links
