### ISSUE TITLE
list is automatically in reverse order when adding core plugin

### ISSUE THREAD

**Issue by jdewane1** [no81no/jplist#161]
First time using this so could be me.  When I add the core plugin and basic script my list is automatically rendered in reverse order.  This is without sort or filter or anything, just opening page in IE11.

This looks like a great plugin with great options, appreciate the work!

<script>
			$('document').ready(function () {
			    $('#demo').jplist({
			        itemsBox: '.list'
				    , itemPath: '.list-item'
				    , panelPath: '.jplist-panel'
			    });
			});
	</script>

**Comment by zzseba78** [comment]
Same problem here... :)

**Comment by no81no** [comment]
The issue is fixed and can be tested using the following page: 
https://github.com/no81no/jplist/blob/master/demo/7-no-sort-test-page.html
