### ISSUE TITLE
range slider multiple filter

### ISSUE THREAD

**Issue by luys** [no81no/jplist#162]
Is there any way jquery UI slider would work with multiple data ?

I mean, for example, here http://jplist.com/jqueryuiexamples/range-slider in the first row Arch, despite $85 value, it also would have another $x price value.

So, filtering should be considering all the p.price class values.

**Comment by no81no** [comment]
It's possible to create additional class <p class="price2">$x</price> in HTML, and create additional range slider that has data-path=".price2" to handle this case.
