### ISSUE TITLE
Combine two controls

### ISSUE THREAD

**Issue by oilenrock07** [no81no/jplist#163]
Hi.

Is it possible to combine two controls in jplist?

What Im trying to achieve is to have a dropdown with multiple price range of checkboxes inside.
So im trying to combine jplist.checkbox-dropdown (for dropdown with checkboxes) and jplist.filter-toggle (for price range control)

Please advise. 
Thanks

**Comment by no81no** [comment]
Such control already exists:
http://jplist.com/controls/checkbox-dropdown
