### ISSUE TITLE
Pagination page no elements not loading for deep links

### ISSUE THREAD

**Issue by aa411853** [no81no/jplist#165]
Cannot figure out why the pagination page # elements are not loading when either refreshing current page, or calling page via a deeplink.  Have deepLinking set to true.

In order for page # elements to appear you have to click next button.  However if I change any of the filters the page nos appear without having to proceed to next page first..

See sample link below:

https://www.southernautomart.com/index.php?page=search#bodystyle-filter:path=.SEDAN%204-DR|make-filter:path=default|drivetrain-filter:path=default|paging:number=15

**Comment by no81no** [comment]
Added pagination demo with deep links:
https://github.com/no81no/jplist/blob/master/demo/6-pagination-demo-deep-links.html
