### ISSUE TITLE
Use itemPath as data-path 

### ISSUE THREAD

**Issue by janstieler** [no81no/jplist#166]
Hi,
I need to search through all elements of my article.
For this I have used the class .item for itemPath and data-path but this will crash the jplist plugin.
Now I have to add an unnecessary div only for the searchfunctionality.
Is there a posibility to use the itemPath as data-path?

Cheers

**Comment by no81no** [comment]
Added demo page:
https://github.com/no81no/jplist/blob/master/demo/9-textbox-filter-search-any-text.html
