### ISSUE TITLE
localization functionality

### ISSUE THREAD

**Issue by boulepick** [no81no/jplist#169]
Nice plugin,
i'm currently implementing it in my website and so far it is working great. is the localization available for this plugin, i would like to display the panel and other languages and going through the documentation i do not see the option. It would be great to have localization for this plugin

**Comment by no81no** [comment]
The main purpose of this plugin is sort/filter/pagination functionality. It will be better to use dedicated tools/plugins to perform localization on your website.

**Comment by boulepick** [comment]
Was talking more about the labels for the dropdowns and buttons that are in the jplist-panel, the pagination captions and all other stuff that jplist is generating. Was not talking about localization of the website.

Cheers

**Comment by no81no** [comment]
Thank you for the update. Anyway, I'm trying to restrict the plugin functionality to its main purpose. Localization feature could be better done by a dedicated tool.
