### ISSUE TITLE
Dynamic jplist-drop-down undefined attributes breaks panel

### ISSUE THREAD

**Issue by eformx** [no81no/jplist#170]
I am trying to create a dynamic jplist-drop-down.  The drop down appears on the page; however the panel does not render.  I get **Uncaught TypeError: Cannot read property 'attributes' of undefined jplist.sort-bundle.min.js**  If I remove the dynamic jplist-drop-down and try to create my own select on the page page I get the same error.  If I remove the script <script src="script/jplist.sort-bundle.min.js"></script> my select works.

**Comment by no81no** [comment]
Added demo page with dynamic sort control:
https://github.com/no81no/jplist/blob/master/demo/14-dynamic-sort-control.html
