### ISSUE TITLE
Range slider for php mysql

### ISSUE THREAD

**Issue by PJanisio** [no81no/jplist#172]
Hello, 

I would like to use jquery UI range slider, it works on clean HTML site filtering by html elements. But i have no idea how to set it together with php and mysql.
I have chosen checkboxgroupfilter.php because I can set control-name there.

Created new function:

function rangeslider($status){
named it, and set-up query column.

setted up my index.html controls, but nothing changes. I have doubts if it works with dynamic data or only with static html.

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#16

**Comment by no81no** [comment]
Added range slider control and demo page:
https://github.com/no81no/jplist-php-mysql/blob/master/5-range-slider.html
https://github.com/no81no/jplist-php-mysql/blob/master/server/controls/range-slider.php
