### ISSUE TITLE
Arrow color

### ISSUE THREAD

**Issue by marcus-andersson** [no81no/jplist#175]
Hi,
How do I change the color of the arrow in a dropdown menu?

**Comment by marcus-andersson** [comment]
Clarification:
It is regarding a dropdown menu to jPlist filtration.

**Comment by no81no** [comment]
You can use the following css:

/**
* new arrow color is green
*/
.jplist-drop-down .jplist-dd-panel:after {
    color: green;
}

/**
* new arrow hover color is red
*/
.jplist-drop-down:hover .jplist-dd-panel:after {
    color: red
}
