### ISSUE TITLE
JPLIST Single box for title and description search

### ISSUE THREAD

**Issue by shariq619** [no81no/jplist#177]
I want a single box to search for both title and description in jplist php mysql 

						<div class="text-filter-box">
																			
							
												
							<input 
								data-path=".title, .desc" 
								data-button="#title-search-button"
								type="text" 
								value="" 
								placeholder="Filter by Title" 
								data-control-type="textbox" 
								data-control-name="title-filter" 
								data-control-action="filter"
							/>
												
							<button 
								type="button" 
								id="title-search-button">
								<i class="fa fa-search"></i>
							</button>
						</div>

Something like this

**Comment by shariq619** [comment]
![php mysql and html demo jplist jquery data grid controls](https://cloud.githubusercontent.com/assets/15646752/13910919/8ed49d00-ef4b-11e5-83b8-2f38b182e598.png)

**Comment by shariq619** [comment]
Is any one to help?

**Comment by PJanisio** [comment]
Im curious also why this is not working in php and mysql. Tested today and no effects.

@shariq619 
did you found a solution?

Related with.
#67

**Comment by no81no** [comment]
To achieve it the following control should be changed:
https://github.com/no81no/jplist-php-mysql/blob/master/server/controls/textbox.php

 For example,
$result->query = " (title like ? or  description like ?) ";

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#13
