### ISSUE TITLE
Wordpress plugin instructions needed & feature request

### ISSUE THREAD

**Issue by geo2arc** [no81no/jplist#18]
Hi, I installed the wordpress plugin, activated, visited the settings page and... I wonder how I can use it! I would appreciate some basic instructions or example. Do I create page and copy/paste code? Is there a shortcode for pages/template available?
Adding more cotrols to the WP plugin would be very useful, especially more complex ones, for example range filter, star rating, freetext with autocomplete combined for title/content, search tags and custom fields with autocomplete, dropdown selection, button filter, date filter etc. Too much to ask, I know, but very useful for WP frontend developers.
It looks like a great plugin, and has a lot of potential.
Thank you!

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-github-wordpress-plugin#5
