### ISSUE TITLE
"Table with Sortable Columns" demo?

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#180]
I see some new activity last few days, thanks for the updates!

However, in the new version, I can't find a *.html example for "Table with Sortable Columns".
http://jplist.com/layoutexamples/table-with-sortable-columns

Could you include this one?

**Comment by no81no** [comment]
The demo is added here:
https://github.com/no81no/jplist/blob/master/demo/11-table-with-sortable-columns.html

**Comment by Silvester20** [comment]
Thank you very much!
