### ISSUE TITLE
Pagination with data-control-storage="false" not working

### ISSUE THREAD

**Issue by b0hdy** [no81no/jplist#181]
Hi, I have problem with pagination. When I want to use **data-control-storage="false"** on pagination settings (bootstrap), it´s not working. When I refresh page, pagination won´t load.
PS: Using PHP Data Source

Thank you.

**Comment by no81no** [comment]
Have you defined storage settings like described in the docs?
http://jplist.com/documentation/js-settings#storage

**Comment by b0hdy** [comment]
Yes. Everything else working, filtering, etc. But I don´t want to save current page and want to always start with page number one.

**Comment by no81no** [comment]
Actually, you need to do data-control-storage="false" (and not true) like described here:
http://jplist.com/controls/bootstrap-pagination-control#settings

**Comment by b0hdy** [comment]
Sorry, I was wrong. I have set data-control-storage="false" on UL pagination. Try your demo "1-php-mysql-html" with server, set storage and data-control-storage and you wil see.

**Comment by no81no** [comment]
OK, I'll check it.

**Comment by b0hdy** [comment]
Any solution?

**Comment by no81no** [comment]
The issue is fixed (in js):
https://github.com/no81no/jplist/blob/master/demo/php-mysql-demos/7-php-mysql-html-with-localstorage.html

**Comment by b0hdy** [comment]
Good, what file (js) has been modifed?

**Comment by no81no** [comment]
You should take the relevant files from the dist folder (depending on controls you're using):
https://github.com/no81no/jplist/tree/master/dist/js

**Comment by no81no** [comment]
Please take the scripts from dist folder again now. I forgot to upload them to github :)

**Comment by b0hdy** [comment]
Now have errors: 
jplist.sort-bundle.min.js:10 Uncaught TypeError: Cannot read property 'attributes' of undefined

**Comment by b0hdy** [comment]
Ok, thank you, it´s working. But now it´s problem with boot-items-per-page-dropdown, when you don´t select number of post on page, results won´t show, but when you select number of post on page and refresh page, result will show.

**Comment by b0hdy** [comment]
So still not functioning properly fully jplist.bootstrap-pagination-bundle.min.js. :(

**Comment by no81no** [comment]
Can you share the link?

**Comment by b0hdy** [comment]
I can't, because I have it on localhost. But your demo PHP with MySQL and localstorage (last edited) has still bug, when you select another per page and you are go to another page (no first) and refresh page, still current page stay saved.

**Comment by no81no** [comment]
I've created a demo page here:
https://github.com/no81no/jplist/blob/master/demo/php-mysql-demos/9-bootstrap-pagination-bundle-demo.html
It seems to work OK. 
Please compare your html with this demo.

**Comment by b0hdy** [comment]
Still not working, after refresh page on another page (ex. 2), result is empty. I am using:
jplist.core.min.js
jplist.bootstrap-pagination-bundle.min.js       
jplist.bootstrap-filter-dropdown.min.js
jplist.textbox-filter.min.js
jplist.bootstrap-sort-dropdown.min.js
jplist.history-bundle.min.js
jplist.list-grid-view.min.js
jplist.preloader-control.min.js

**Comment by no81no** [comment]
I'm not sure why it doesn't work on your end. Maybe the best options would be to recreate the demo page I provided in your environment and compare these pages.

**Comment by b0hdy** [comment]
I tried your demo and compare html, it´s same, but when i select another per page and go to second page and then refresh page, per page will reset OR when I for the first go to second page and then select another per page and refresh page, current page (2) stay saved, so there is still bug.

**Comment by no81no** [comment]
So you use 2 different pages with jplist with local storage settings?

**Comment by b0hdy** [comment]
No, I thought on the same page. I am using JPlist with localstorage and PHP html data source. When I select on pagination page (2), then select "per page 10" and refresh page, current page is still 2. If I do this conversely "per page 10" will reset back to "per page 3" but current page is first. It´s so complicated. :)

**Comment by b0hdy** [comment]
I´ll try to create demo and upload on ftp.

**Comment by b0hdy** [comment]
Check it out, what I wrote [http://www.comely.cz/code/jplist/demo/php-mysql-demos/1-php-mysql-html.html](url)

**Comment by no81no** [comment]
Thank you for the uploaded demo, I'll check it.

**Comment by b0hdy** [comment]
Any progress?

**Comment by no81no** [comment]
The issue is fixed.
You can download:
- js files from https://github.com/no81no/jplist/tree/master/dist/js
- php from https://github.com/no81no/jplist/blob/master/server/domain/pagination.php

**Comment by b0hdy** [comment]
Ok, that's fine. I'll try it and give you feeeback.

**Comment by no81no** [comment]
Great :)

**Comment by b0hdy** [comment]
Now, it's work very good. Thank you!! :+1: :)

**Comment by no81no** [comment]
I'm glad that it's OK. 
I've added 530 integration tests, so now it could be easier to avoid bugs after future changes.
