### ISSUE TITLE
Bootstrap pagination bundle - animate to top - bottom panel

### ISSUE THREAD

**Issue by b0hdy** [no81no/jplist#182]
Hello, I found bug. It´s in Bootstrap pagination bundle, when you have pagination in bottom panel and you have set data-control-animate-to-top="true", page won´t scroll to top.

**Comment by no81no** [comment]
Thank you for reporting this issue.
It's fixed - please download the following file:
https://github.com/no81no/jplist/blob/master/dist/js/jplist.core.min.js
