### ISSUE TITLE
Bootstrap Dropdown Filter not working

### ISSUE THREAD

**Issue by sgaul1** [no81no/jplist#183]
`jPList - jQuery Data Grid Controls 5.2.0.6` is the header of the js file I am using, but it causes the rest of the controls (pagination, sorting, etc...) to stop working.

**Comment by no81no** [comment]
You should download the latest versions of all other controls to make it work.

**Comment by sgaul1** [comment]
I do have the latest versions.  I am using only the bootstrap controls as of right now.
`jPList - jQuery Data Grid Controls 5.2.0.5` for sorting
`jPList - jQuery Data Grid Controls 5.2.0.12` for pagination

**Comment by no81no** [comment]
You can compare your code with demo pages to find out the differences:
https://github.com/no81no/jplist/tree/master/demo

**Comment by sgaul1** [comment]
I updated the core file and was unsuccessful in fixing this issue.  It seems that all of the controls stop working only when i include `jplist.bootstrap-sort-dropdown.min.js` on the page.  If it is commented out the remaining controls will continue to work

**Comment by no81no** [comment]
So the issue is only with jplist.bootstrap-sort-dropdown.min.js? Bootstrap pagination works well?

**Comment by sgaul1** [comment]
I'm sorry, I copied the wrong file name. `jplist.bootstrap-filter-dropdown.min.js` Is the file I am having issues with.  If this file is not included in the project, both `jplist.bootstrap-pagination-bundle.min.js` and `jplist.bootstrap-sort-dropdown.min.js` work perfectly.

**Comment by no81no** [comment]
OK, I'll check this control and let you know.

**Comment by no81no** [comment]
Please use the following working demo:
https://github.com/no81no/jplist/blob/master/demo/13-bootstrap-mixed.html

**Comment by sgaul1** [comment]
Thank you for your help!  The problem is coming from my HTML, as I am not calling something correctly.

**Comment by sgaul1** [comment]
`data-control-type="boot-filter-drop-down"
 data-control-name="category-filter"
 data-control-action="filter"`

This is where I'm runnning into issues

**Comment by no81no** [comment]
You can try starting from the demo page and replace its parts with your own code step by step. This way you may figure out the issue with your HTML.

**Comment by sgaul1** [comment]
I am using an asp:GridView to get data from an SQL database, and it seems this is causing the issue.  I took my code for the GridView and replaced it in the demo and it no longer worked.  Should i just build a regular table?

**Comment by no81no** [comment]
Please use jsFiddle, jsBin, or Codepen to recreate you issue test case HTML.
I should see the issue so I could help you..

**Comment by sgaul1** [comment]
I took a few days to fiddle around with it, and i actually used `jplist.filter-toggle-bundle.min.js` and styled it to look like the Bootstrap dropdown, and it is now working.  Thank you for your help though!

**Comment by no81no** [comment]
I'm glad that it works now 👍
