### ISSUE TITLE
resetting panel sort-select dropdowns feature

### ISSUE THREAD

**Issue by boulepick** [no81no/jplist#187]
Good day,
i'm trying to use the sort-select with select2 dropdowns plugins. it is working ok but the issue that i'm having now is the reset button does not work on the select2 options as it has it's own method to reset the dropdown. And if I trigger the reset of select2 manually, it ends up making two calls to the server, the first one with an error response.  is there a way to add the option for other plugins to incorporate this plugin or provide a way to make this work with select2.

Thank you

**Comment by mariojfduarte** [comment]
Hi there,

I solved my problem by having two different names on the "control-name" attribute

**Comment by no81no** [comment]
Great, I'm glad that it works for you.
Please close the issue.

**Comment by boulepick** [comment]
HI Mariojfduarte, can you tell me hiw exactly you did it.
