### ISSUE TITLE
Dynamically refresh data of loaded list without

### ISSUE THREAD

**Issue by youssoupha** [no81no/jplist#189]
Hello, 
First, thank you for this plugin.
I was looking for a way to update jplist data after this data is modified in DOM.
For exemple after having used a checkbox to update an attribute for one element in the list.

I've noticed that a modelChanged event is triggered when using commands add or del, is there other commands or a way to trigger this events manually ?

Thank you for your time by advance.

**Comment by no81no** [comment]
Hi,
Please update this issue according to the following guidelines:
https://github.com/no81no/jplist/wiki/Reporting-issues
