### ISSUE TITLE
Controls don't display 

### ISSUE THREAD

**Issue by suntrop** [no81no/jplist#190]
I can't get jPlist to work on my new site. Had it working without problems on another site, but now nothing works.
I can't see anything of jPlist … for example the controls won't show up.

https://jsfiddle.net/suntrop/va2mrtp8/2/
(Hope I've setup that fiddle correctly, first time using it)

I have just copied the demo code, but there is no pagination.

**Comment by no81no** [comment]
You just used wrong js file:
You used: https://cdnjs.cloudflare.com/ajax/libs/jplist/5.2.0/js/jplist.bootstrap-pagination-bundle.min.js
The right one: 
https://cdnjs.cloudflare.com/ajax/libs/jplist/5.2.0/js/jplist.pagination-bundle.min.js

Demo: https://jsfiddle.net/no81no/f1br1d6m/10/

**Comment by suntrop** [comment]
Well, that is somewhat … embarrassing :( 

Changed it and of course it works.

Thanks for your help!!

**Comment by no81no** [comment]
You're welcome :)

**Comment by leodsgn** [comment]
I had the same problem with the version in bower. I had to use the link that @1rosehip suggested above to make it work.

Thanks!
