### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by manojyahampath** [no81no/jplist#192]
Warning: Invalid argument supplied for foreach() in FILEPATH/domain/action.php on line 24

Warning: Invalid argument supplied for foreach() in FILEPATH/domain/action.php on line 24

Warning: Invalid argument supplied for foreach() in FILEPATH/domain/action.php on line 24

Fix this

**Comment by no81no** [comment]
Follow jPList guidelines for opening issues:
https://github.com/no81no/jplist/wiki/Reporting-issues
