### ISSUE TITLE
modified json request

### ISSUE THREAD

**Issue by fouriejj** [no81no/jplist#194]
Hi.

I am using the handlebars template. When we filter we get a json response from /server-json.php.

I have added some custom json to that that I would need to parse outside of Jplist , but it needs to be generated by jplist based on the filters. (Graphs).

Can you tell me the list of files I would need to edit to add this, and if you would be so kind to tell me how I would access it? I have reviewed the API and it doesn't seem to assist in this case.

**Comment by fouriejj** [comment]
or if you can tell me how to access the objects that would also work. ie:
  console.log(dataItem.content.Gender); 
doesn't work.

**Comment by no81no** [comment]
Please check the 'Redraw Callback' function:
http://jplist.com/documentation/js-settings/redraw-callback-function

**Comment by fouriejj** [comment]
How does this help me access the JSOn data? Show me an example.

**Comment by no81no** [comment]
**collection** variable contains the data you get from the server:

```
<script type="text/javascript">
$('document').ready(function(){

    $('#demo').jplist({

        //main options
        itemsBox: '.list' //items container jQuery path
        ,itemPath: '.list-item' //jQuery path to the item within the items container
        ,panelPath: '.panel' //panel jQuery path

        ,redrawCallback: function(collection, $dataview, statuses){

             console.log(collection);
        }
    });
});
</script>
```
