### ISSUE TITLE
Connect To WP Database

### ISSUE THREAD

**Issue by mangomkt** [no81no/jplist#195]
I am wondering if it will load all 1000 posts then hide them or will it only load a few at a time??

**Comment by no81no** [comment]
It loads a few at a time via ajax..

**Comment by mangomkt** [comment]
It looks like it is loading all then hiding them...I do not have the WP
version... where can I download it

**Comment by no81no** [comment]
The old WP version is not available for now. It's under some process of maintenance and rewrite.
