### ISSUE TITLE
Multi word search in desc textbox 

### ISSUE THREAD

**Issue by hailey511** [no81no/jplist#196]
Hi,

 I wanted to have multi word filter for desc textbox filter with ',' separator or space. Is it actually possible ?

**Comment by no81no** [comment]
Hi,
Multi word filter is possible in 'advanced' mode with 'or' separator. ',' separator or space is not supported for now. Please check the docs here:
http://localhost:49152/controls/textbox-filter-settings

Thanks,

**Comment by mixtum** [comment]
If I have...
data-mode="advanced"
then where I should put "or", "and" or "not" ?

**Comment by no81no** [comment]
Inside the text field while you are searching..

**Comment by mixtum** [comment]
I see..

But is there any chance to translate these words? My website is not in English and end customers does not know how to use "and" / "or" words :)

Or any other way so that you could search with multiple search terms with "or" logic?

**Comment by no81no** [comment]
It's possible now to change operator names in advanced mode and have multiple operators using data-or, data-and and data-not parameters:
http://jplist.com/documentation/control-settings/textbox-filter

Please download:
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.core.min.js
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.textbox-filter.min.js
