### ISSUE TITLE
Some of your demo pages are broken

### ISSUE THREAD

**Issue by Beedrew** [no81no/jplist#198]
For example, this one:
http://jplist.com/datasourcesexamples/php-mysql-demo

**Comment by tduncandesign** [comment]
+1

**Comment by DDiepMSTR** [comment]
+1. I was trying to find the asp.net demo to hook it up.

**Comment by no81no** [comment]
Sorry for that, it will be fixed in the near future.
This issue is related to hosting and infrastructure change of the jplist website.

**Comment by janstieler** [comment]
Hi,
this example had also some problems:
http://jplist.com/layoutexamples/list-grid

Cheers

**Comment by no81no** [comment]
The website is restored and should work OK now.
Please let me know if you have issues with it.
