### ISSUE TITLE
Filter and pagination combined

### ISSUE THREAD

**Issue by caneta** [no81no/jplist#204]
Hi @no81no.
Is it possible to combine jplist pagination and a dropdown filter on the same list of objects in a page?
I would like to have pagination and a dropdown filter that, when used, modify the pagination accordingly.
Is there a way to set up something like this?
Thank you.

**Comment by no81no** [comment]
Sure, you can use any controls together in any combination.
Here is example with dropdown filter, pagination and other controls:
http://jplist.com/controlsexamples/drop-down-filters-ul-li

Getting started:
http://jplist.com/documentation

**Comment by caneta** [comment]
Ok sorry, my fault.
I didn't get how to put multiple control panels in different positions on the page.
Thank you for the example, it worked!
