### ISSUE TITLE
Total number of filtered items

### ISSUE THREAD

**Issue by mixtum** [no81no/jplist#207]
I can use pagination to show number of paginated pages after filtering, but how to show total number of filtered items (simple text information like "found XX items").

**Comment by PJanisio** [comment]
Im using pagination-info to display it :)

`<div class="jplist-label" data-type="Found: <b>{all}</b> items" data-control-type="pagination-info" data-control-name="paging" data-control-action="paging"></div>`

**Comment by no81no** [comment]
For pagination you can use pagination result control:
http://jplist.com/controls/pagination-info
http://jplist.com/documentation/control-usage/pagination-info

For filters you may use counter control: 
http://jplist.com/controls/counter
http://jplist.com/documentation/control-usage/counter

**Comment by mixtum** [comment]
Thanks.
