### ISSUE TITLE
Text-filter issue with Google Chrome

### ISSUE THREAD

**Issue by momessog** [no81no/jplist#209]
Hi, 
I detected an small issue in Text Filter using Google Chrome Version 51.0.2704.106 (64-bit)
The browser don't allow commands to select all text, like Ctrl + A or Shift + Left, in text filter box, even the key Home doesn't go to the text beginning.
In Mozilla Firefox works fine all this commands.
There are already a closed issue about that but in my case a "clear button" is out of question for the system.
Any suggestion about how to fix this browser incompatibility?
Thanks.

**Comment by no81no** [comment]
The issue is fixed, please download the file again:
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.textbox-filter.min.js
