### ISSUE TITLE
jpList in combination with 'Zurb Foundation Tabs' causes bug

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#210]
**Case**:
I want to search between tab-titles. Those tabs are created with Zurb Foundation for sites (latest) and the searching is done by 'jpList textbox filter'.

**Problem**:
After initializing jpList on the Foundation tabs, the tabs are not working anymore.
jpList is detaching the `<li>`elements of the tab and placing it **outside** the `<ul></ul>` elements.

**Possible solution**:
When jplist detach the `<li>`-elements, it should attach them back **inside** the `<ul></ul>` element. (The `<ul> & <li>` elements are created by the Foundation Tabs plugin)

**Example**: https://jsfiddle.net/b9hsy9ez/1/

**Comment by no81no** [comment]
Working demo:
https://jsfiddle.net/no81no/s2n9dmpt/

All you need is to change 
`itemsBox: '.jplist'`
to
`itemsBox: '#example-vert-tabs'`

**Comment by Silvester20** [comment]
Didn't thought it was so easy, thank you very much!

**Comment by no81no** [comment]
You're welcome :)
