### ISSUE TITLE
reset button doesn't clear date range jquery ui filter?

### ISSUE THREAD

**Issue by mistyn8** [no81no/jplist#211]
As per the title.. reset button doesn't clear date range jquery ui filter?

**Comment by no81no** [comment]
The issue is fixed.
Please download the following js file:
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.jquery-ui-bundle.min.js

**Comment by mistyn8** [comment]
excellent, thanks.

**Comment by no81no** [comment]
Please close this issue if all is well.
