### ISSUE TITLE
Handlebars multiple Checkbox options

### ISSUE THREAD

**Issue by Extracreative** [no81no/jplist#212]
Moved back from jplist-php-mysql

I notice for Checkbox Path Filter Control, its possible to use checkbox to return items with multiple keyword1 options i.e Architecture and Christmas, but in Handlebars I can only return items with only one keyword1 i.e only return Architecture

how can I return keyword1 where the item has Architecture and Christmasas an option in the Handlebars version

**Comment by no81no** [comment]
Please check the following demo with checkbox path filter:
https://github.com/no81no/jplist/blob/master/demo/php-mysql-demos/1-php-mysql-html.html
Does it answers the need?
