### ISSUE TITLE
Could dates be updated to allow short and long month names?

### ISSUE THREAD

**Issue by mistyn8** [no81no/jplist#213]
Could dates be updated to allow short and long month names?

I can't seem to be able to get 10th January 2016.. or 10 Jan 2016 to filter, but reverting to 10 01 2016 is fine.

thanks.

**Comment by no81no** [comment]
Unfortunately this is not possible. The workaround could be to have 2 formats together. One like **10th January 2016** will be visible, and another like **10 01 2016** will be hidden. The control will work with the hidden date.
