### ISSUE TITLE
Failure after empty the list and appending a new item

### ISSUE THREAD

**Issue by Silvester20** [no81no/jplist#216]
Hi there,

So I used the new and very nice feature the 'empty' command to empty the list at once, requested at https://github.com/no81no/jplist/issues/214

I am not sure but there is maybe a bug with this feature. When I empty the list everything works fine. However, when I add a new item using the add-feature, after the empty feature, all the previous items before empty'ing are back in the list again.

So just like this:
1. Initialize a jplist pagination control.
2. Add a item using the 'add'-command of jplist.
3. Empty the list using the 'empty'-command of jplist.
4. Add a item using the 'add'-command of jplist. (Result of this all the deleted items from step 3 are back again)

I hope you understand what I mean otherwise I will post  fiddle :)

**Comment by no81no** [comment]
Thank you for reporting this, it's fixed.
Please download core js again:
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.core.min.js

**Comment by Silvester20** [comment]
Seems to work now, thank you very much!

**Comment by no81no** [comment]
You're welcome :)
