### ISSUE TITLE
number of visible pagination button

### ISSUE THREAD

**Issue by oke007** [no81no/jplist#217]
hey, how can i control number of visible pagination button if i have 100 page with each contain 20 data list, by default its showing 100 buttons that is not look good.
any solution ?

**Comment by no81no** [comment]
Depending on the case you may use data-range attribute or 'items per page dropdown' control settings:
http://jplist.com/documentation/control-settings/pagination
http://jplist.com/documentation/control-settings/items-per-page-dropdown

**Comment by oke007** [comment]
hey, problem has been solved now, first solution was suitable for me. great work keep it up highly recommended.
