### ISSUE TITLE
How to reset single filter in JPList

### ISSUE THREAD

**Issue by AmolInv** [no81no/jplist#222]
Hi,

Thanks in advance.
Can anyone help me "How to reset single filter in JPList?"
Currently JPList clear the all filters, however I have given Reset option under each filter and want to clear a single filter.

**Comment by no81no** [comment]
Unfortunately it's not possible out of the box using the reset button control. But you may create a custom button once clicked it resets your filter. The implementation depends on the kind of filter you need to reset.

**Comment by iManu** [comment]
Hi @1rosehip, 
Can you explain how to implement the custom button you are talking about ?
For example I need to reset only range slider filter but not the others.
Thanx !
