### ISSUE TITLE
Sort text containing French Accents

### ISSUE THREAD

**Issue by BDDinh** [no81no/jplist#223]
If you have french accents at the beginning of a text, when sorted ascending, that item will be appear at the end of the sorted list.

For example:

<p class="title">ABCD</p>
**<p class="title">ÉFGH</p>**
<p class="title">IJKL</p>
<p class="title">LMNO</p>

sorted will become:

<p class="title">ABCD</p>
<p class="title">IJKL</p>
<p class="title">LMNO</p>
**<p class="title">ÉFGH</p>**

**Comment by no81no** [comment]
Implemented. Please download https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.core.min.js again.

**Comment by BDDinh** [comment]
Will do and thank you!

**Comment by no81no** [comment]
You're welcome. Please close this issue if all is well.

**Comment by BDDinh** [comment]
Hello,

I plan to integrate the new version on Tuesday and test it thoroughly. I'll close it then. And thank you again!

**Comment by no81no** [comment]
Sure, no problem
