### ISSUE TITLE
Button Path Filters Group not accepting multiple filters

### ISSUE THREAD

**Issue by JessePimenta** [no81no/jplist#228]
Although I have followed the format for setting up group-filtering, I still am only able to filter by one result at a time. I have tried to manually add settings to each button but still getting same results.
so if i want to select for example 30, 60, and another query, I am only able to choose 30 OR 60. I need to choose both and another query. Can anyone point out what i'm doing incorrectly?
 
Buttons:
![screen shot 2016-10-20 at 8 25 59 pm](https://cloud.githubusercontent.com/assets/12524608/19585717/a29a18dc-9703-11e6-9111-fcaa0ab87aa3.png)

Results:
![screen shot 2016-10-20 at 8 26 30 pm](https://cloud.githubusercontent.com/assets/12524608/19585720/a7f2d832-9703-11e6-84a1-29cad551fc4a.png)

**Comment by no81no** [comment]
Please follow [jPList guidelines](https://github.com/no81no/jplist/wiki/Reporting-issues) for opening issues and  use jsFiddle, jsBin, or other such service to share your test case.
