### ISSUE TITLE
How to make the range slider dynamic? If i reinitialise the plugin then, it gives me duplicate data. I get the data via ajax call in json format which i use to update my list. But only when i try to update the price range slider it gives me duplicate data. 

### ISSUE THREAD

**Issue by nixondsz879** [no81no/jplist#231]

**Comment by no81no** [comment]
Please consider using add / remove items using API:
http://jplist.com/documentation/api-add-one-item
http://jplist.com/documentation/api-add-range-of-items
http://jplist.com/documentation/api-remove-one-item
http://jplist.com/documentation/api-remove-range-of-items
http://jplist.com/documentation/api-remove-all-items

**Comment by nixondsz879** [comment]
I appreciate the quick response. But can u please tell me how do i update range-slider with new values?

**Comment by no81no** [comment]
Please create your test case in jsFiddle, jsBin, or Codepen so I can help you.

**Comment by nixondsz879** [comment]
Thank you for the help. But i managed to solve the issue.

I had used ".js-panel" for "panelPath" in some areas instead of ".jplist-panel" and that was the reason why all multiple filters were not syncing together.
