### ISSUE TITLE
Multi checkbox drop down filter

### ISSUE THREAD

**Issue by buymotors7** [no81no/jplist#24]
Hello.
Can you implement feature "Multi checkbox drop down filter" in the box ?

I tried to add from this projects
http://acquisio.github.io/bootstrap-dropdown-checkbox/
http://ivaynberg.github.io/select2/

no good for now.
maybe you do it just in few minutes/hours? :)

**Comment by no81no** [comment]
Checkbox dropdown filter control:
https://jplist.com/controls/checkbox-dropdown#preview

Thanks,
