### ISSUE TITLE
Date picker range filter

### ISSUE THREAD

**Issue by Debby37** [no81no/jplist#25]
Dear Miriam,

Could you update the date picker range filter with the following possibility:
In the prev field I would like today's date to be selected, when somebody opens my calendar and in the next field I would like the max date to be selected.

So everybody lands on today's events.
After that they can pick their own prev and/or next date(s) within the min/max dates.

Hope you understand my question and hope you can help me.

Debby

**Comment by no81no** [comment]
Implemented:
http://jplist.com/documentation/control-settings/date-picker-range-filter
