### ISSUE TITLE
display info if filters are active 

### ISSUE THREAD

**Issue by Flaschenzug** [no81no/jplist#47]
just another Idea,
how about a bundle (maybe in the reset bundle) that shows, when filters are active - and with the possibility to clear / reset the filters?

**Comment by Flaschenzug** [comment]
Do you know what i mean?
And are there any plans to realize this feature ?
Thanks :+1:

**Comment by no81no** [comment]
Yes, the example at  zalando.co.uk is nice and clear, and I like the idea.
I'll try to implement it, but I still have no estimation date for it .

**Comment by Flaschenzug** [comment]
Great! Happy to hear that.
Thanks a lot!

**Comment by Flaschenzug** [comment]
Any progress with this idea?
If I can help let me know! Best

**Comment by Extracreative** [comment]
I've done it here http://beta.refineby.com. you just need a bit of js

**Comment by no81no** [comment]
Reset button control can be used to clear the filters to their defaults:
http://jplist.com/controls/reset-button

**Comment by Flaschenzug** [comment]
so this feature won't come, it's a pitty. thanks for your reply
