### ISSUE TITLE
trigger event

### ISSUE THREAD

**Issue by ylahav** [no81no/jplist#54]
is it possible to trigger an event - 'data changed' or 'redraw'?

**Comment by no81no** [comment]
There are several events that you can use in the following way:

var api = $('#demo').data('jplist')
    ,events = api.observer.events;

api.observer.on(events.statusChanged, function(){
    console.log(arguments);
});

Events can be found here:
https://github.com/no81no/jplist/blob/master/jplist-core/source/js/app/events/pubsub.js

Please check them, maybe one of them will be useful for you.

**Comment by stowns** [comment]
I think @ylahav may have been asking if there was a way to trigger a redraw event not *react* to an event

**Comment by ilune** [comment]
+1

**Comment by ilune** [comment]
just found it \o/

`var api = $('.jpfilter').data('jplist')
        api.observer.trigger(api.observer.events.unknownStatusesChanged, [false]);`
