### ISSUE TITLE
content in the .list

### ISSUE THREAD

**Issue by Flaschenzug** [no81no/jplist#55]
I tried to put some other content than .list-items in the .list container:

div class="list">
 div class="newsitem col-xs-12 col-md-6 sponsor first even">test 1</div> 
 div class="clearfix"></div>
 div class="newsitem col-xs-12 col-md-6 sponsor first even">test 2</div>
 div class="newsitem col-xs-12 col-md-6 sponsor first even">test 3</div>
/div>

But jplist removes the item. Is there a way to keep an item (in position)?

In this care jplist removes the clearfix tag.

**Comment by no81no** [comment]
Unfortunately this is not possible.
