### ISSUE TITLE
Question before purchase Autocomplete

### ISSUE THREAD

**Issue by Sheilven** [no81no/jplist#56]
Hello,
I am going to buy the plugin "Autocomplete" https://jplist.com/controls/autocomplete#preview but i have one question after purchase:
Actually i use your plugin with MySql, in server-html.php i load the data from mysql. The autocomplete can read this dates from MySQL?
Thanks in advanced

**Comment by no81no** [comment]
Hello,
Thank you for the interest.
Autocomplete control supports php/mysql as following:
- php/mysql html version
- php/mysql with json/handlebars/mustache/etc.
- php/-mysql with xml/xslt

All demo pages are included into the archive.

Thanks
