### ISSUE TITLE
Bug? Some controls don't work in iPad

### ISSUE THREAD

**Issue by mindbodyheart09** [no81no/jplist#57]
Tried a few demos on iPad and at least some controls don't work,

**Comment by no81no** [comment]
Please provide more details about this issue. What exactly controls don't work? Maybe screenshot?

**Comment by mindbodyheart09** [comment]
iPad Air, 8.1.2(12B440)
Safari, should be the latest version

Below is the sreenshot:

https://www.dropbox.com/s/9c58n0n2edbu6dr/ipad.PNG?dl=0

**Comment by mindbodyheart09** [comment]
Any words? Thanks,

**Comment by no81no** [comment]
Unfortunately I have no iPad to check this issue. I'll investigate it once I'll find a device to test.

**Comment by kevinchevallier** [comment]
I fixed this issue with this: http://touchpunch.furf.com/. Tested on ipad air and android 5.

**Comment by no81no** [comment]
Thank you for the reference. Could you please tell how you fixed it? Just by adding 'UI Touch Punch' library to the page?

**Comment by kevinchevallier** [comment]
Yup, added the plugin into my scripts and *magic*.

**Comment by no81no** [comment]
Thank you :+1:
