### ISSUE TITLE
radio buttons - failure with deeplinking

### ISSUE THREAD

**Issue by Flaschenzug** [no81no/jplist#58]
I just tried to use the radio buttons with the url deeplinking.
The whole filtering ist working quite well, but as soon as I reload the page, the filter is active (radio is checked) but all the items are displayed.

CONFIG:
itemsBox: '.list' 
      ,itemPath: '.newsitem' 
      ,panelPath: '.jplist-panel'
      ,noResults: '.jplist-no-results'
	  ,storage:"cookies"
      ,storageName:"listSortConfig"
      ,cookiesExpiration:-1
      ,deepLinking: true

https://jplist.com/controls/radio-buttons-filters#preview

Can someone reproduce this problem ?

**Comment by no81no** [comment]
Thank you for reporting this issue.
The problem is fixed, please download latest version of jplist-core.min.js and jplist.filter-toggle-bundle.min.js
