### ISSUE TITLE
Deep Linking Demo download

### ISSUE THREAD

**Issue by ProgramacionRS** [no81no/jplist#59]
Where I can download deep linking demo? 

https://jplist.com/otherexamples/deep-linking#paging:number=3|category-filter:path=default|group-filter:path=default|paging:currentPage=0

**Comment by ProgramacionRS** [comment]
https://jplist.com/otherexamples/deep-linking#paging:number=3|category-filter:path=.food|group-filter:path=.group2|colors:pathGroup=.blue|paging:currentPage=0

How I can save filters so that I copy and paste the url, the results are saved ?

Sorry for mi english ! :+1:

**Comment by no81no** [comment]
Hi,
When you select filters the url changes and reflects your selection.  After copy / paste you may see your selected filters. Unfortunately there is not a special download for the deep linking demo, but you can add 'deepLinking: true' property to javascript to get it. 
The full list of javascript options could be found here: https://jplist.com/documentation/js-settings

Thanks

**Comment by ProgramacionRS** [comment]
Ok, thank you! But I have a problem, in the example that I use: https://jplist.com/datasourcesexamples/php-mysql-demo
I add deepLinking: true but all values of the filter: jplist-drop-down, they are not charged in the url when i click about any <li>, what is the problem? :octocat:

**Comment by no81no** [comment]
Please send a link to the page so I could see the issue.

**Comment by Sheilven** [comment]
Hello,
I have the same problem, if i select order by title and after  i select order by date in deep linking show title, i mean, depp linking is always retarded... 
PD: You have my code in your email

**Comment by Sheilven** [comment]
Hello again,
I discover that this error only ocurred in drop-downs, whit checkbox deep linking work.

**Comment by Sheilven** [comment]
Hello again,
I downloand your demo, and create the database (to create the same stage as your web) and it doesn't function.
I believe that this is a bug, try it download your example create the database, enable deep linking and the try, it doesn't work

**Comment by no81no** [comment]
Thank you all for reporting this issue, it will be fixed in the next plugin updates.

**Comment by no81no** [comment]
This issue is fixed, please download last jplist-core.min.js and jplist.filter-dropdown-bundle.min.js

**Comment by ProgramacionRS** [comment]
Please, can you send me last links:
jplist-core.min.js and jplist.filter-dropdown-bundle.min.js ?
thank you!
