### ISSUE TITLE
Disable checkboxe(s) 

### ISSUE THREAD

**Issue by laluuk** [no81no/jplist#60]
Hi there, 
First of all great plugin, really appreciate your work on this.
Sorry I'm not sure if I can explain it well, hopefully I'll make sense. So in the example here https://jplist.com/togglefiltersexamples/checkbox-filters, say I chose Agriculture, I would like Blue to be disabled, since there is no Agriculture and Blue. In the same way if I chose Christmas, I'd like Green and Red disabled. But if I chose Agriculture and Christmas only Blue will be disabled. It'll carry on if there was a third group of checkboxes. Does that make sense, is that possible?
Many thanks in advance.

**Comment by no81no** [comment]
Hi, 
Unfortunately this is not supported for now :(
