### ISSUE TITLE
adding list item at start of jplist

### ISSUE THREAD

**Issue by apikic** [no81no/jplist#62]
Is there a way to add new list item at the start of the list? By using command: 'add' it adds it at the end. Is there a possibility to add it at start by using some command? 

Thanks
Regards

**Comment by no81no** [comment]
There is no way for now, but I'm thinking to add an optional 'index' parameter to the 'add' command. If it exists and the index is not out of range, the item will be added in the given 'index', otherwise it will be added to the end of the list.

Thanks,

**Comment by apikic** [comment]
That would be nice feature. Anyway, great work. 

Regards

**Comment by no81no** [comment]
Fixed, please download last https://github.com/no81no/jplist/blob/master/jplist-core/minified/jplist-core.min.js
