### ISSUE TITLE
Problem with Autocomplete

### ISSUE THREAD

**Issue by Sheilven** [no81no/jplist#63]
Hello,
I buy the pro control "Autocomplete" I integrated in my jplist perfect but when i go to try doesn't work, in the debug console is an error: Uncaught TypeError: Cannot read property 'ui' of undefined  in the line 7.
Additionally i have try to integrate the control counter control, and i have the same error  in this case in line 9.

I can't put here the URL because is a test environment 

Thanks in advance

**Comment by no81no** [comment]
Hello,
Could you send me your page to no81no@gmail.com?
I'll try to check the issue

Thanks,

**Comment by Sheilven** [comment]
Hello,
I can't beacuse it's only online inside my company...
Sorry

**Comment by no81no** [comment]
I'd like to help you, but how should i do it without the code?

**Comment by Sheilven** [comment]
Can you tell me what is the code that you want? I mean I only read the instructions and apply: I put the autocomplete control and JS and CSS files and I put the control in server/controls 

Thanks

**Comment by no81no** [comment]
Please send me the 'view source' of the page and screenshot of the console.

Thanks,

**Comment by Sheilven** [comment]
I send you all the material to your email.

Thanks

**Comment by no81no** [comment]
OK, thank you
As much as I can see all you need to do is to move
<script src="js/jplist.autocomplete.min.js"></script>  below the <script src="js/jplist-core.min.js"></script>,
because all controls should be defined after the main jplist script (jplist core).
Please let me know if it helps

**Comment by Sheilven** [comment]
I put here:

   <div 
      class="jplist-autocomplete"
      data-control-type="autocomplete" 
      data-control-name="autocomplete" 
      data-control-action="autocomplete"
      data-path=".title">
      
      
      <input type="text" placeholder="Filter by Title" />
      
      
      <button type="button">
         <i class="fa fa-search"></i>
      </button>			
   </div>
   <br><br>
							 
		   
		<div class="list box text-shadow">
   
       </div>

And it doesn't work :(

**Comment by no81no** [comment]
Please move  '<script src="js/jplist.autocomplete.min.js"></script>' after '<script src="js/jplist-core.min.js"></script>'

**Comment by Sheilven** [comment]
Thanks!
Now it work! Last Question can I modify the dropdown that appears when i search? Now it show me a lot of information

**Comment by no81no** [comment]
I'm not sure I understand the question, could you please explain it with more details?

**Comment by Sheilven** [comment]
Hello again and sorry for my questions.
When i search, the autocomplete show a dropdown this dropdown has the same appear as the main content. 
¿Can I modify the dropdown?
In your example it means to show only the title (Calendar,Architecture...) and not the description.

Thanks in advance

**Comment by no81no** [comment]
For now the autocomplete dropdown shows exactly the same items as defined in the list. But it's possible to control it's visibility via css, for exampe you may hide description bu using the following css:

.autocomplete-box .block{
  display: none;
}

**Comment by Sheilven** [comment]
Thanks!
You can close :+1:

**Comment by no81no** [comment]
You're welcome :)

**Comment by Chalfouh** [comment]
hello, this is a great plugin, i have a question for you:
what are the caching capability of the datasource
