### ISSUE TITLE
Call to a member function fetchColumn() on a non-object 

### ISSUE THREAD

**Issue by smasher511** [no81no/jplist#64]
I've setup the php/mysql demo on my server, got the database settings correct, but I get no Results and this error. In web console I get only noise.png error.

**Comment by datalynk** [comment]
The noise.png error relates to an incorrect path in the Stylesheet.

Open the JPList /css/styles.min.css file, search '/content/img/common/noise.png' replace with '../img/common/noise.png'

**Comment by no81no** [comment]
Hi,
As I wrote in the issue #73, It seems that $this->db->query($query) takes value of false and can't call on it fetchColumn(). Maybe there is something wrong with the sql query so please try to run this query on mysql directly and check if it works.

**Comment by hossam2015** [comment]
changing the name from Item to item fixes this problem in all the files

**Comment by no81no** [comment]
The table name is moved to 'config.php' so it will be convenient to modify it:
https://github.com/no81no/jplist/tree/master/jplist-data-sources/php-mysql/server
