### ISSUE TITLE
Feature: Access to Events/Methods for Custom Controls

### ISSUE THREAD

**Issue by micahlisonbee** [no81no/jplist#65]
This is a great plugin, the one thing it lacks, where other similar plugins make up, is the ability to control the actions through custom javascript. Meaning, having access to the methods() in jQuery or JS would be great so we can filter/sort/go to pages/etc... with our own buttons and code.

Thanks!

**Comment by kevinchevallier** [comment]
+1, it would be nice indeed.

**Comment by no81no** [comment]
It's possible to create custom addons for jPList.
I've started a documentation about it here:
http://jplist.com/documentation/how-to-create-a-basic-jplist-plugin

Also there are many examples here:
https://github.com/no81no/jplist/tree/master/src/addons
