### ISSUE TITLE
Items are displayed in different succession in Firefox/Chrome

### ISSUE THREAD

**Issue by kowalski90** [no81no/jplist#66]
I use jpList to filter through div's. Firefox displays them exactly like they are in the code and how it's supposed to:

1   2   3   4   5   6

Chrome, on the other hand, displays them something like this

6   1   2   5   4   3

I can't figure out why/how is this happening. Would greatly appreciate any idea.

I have replicated the issue on a different system and it acts in the same exact way. I have tried to find such an issue with jpList demo examples and couldn't. They work like they should, regardless of the browser. It might be something I'm overlooking in my setup.

You can see it in action here: www.ravello.com/hotels/ (load the page in Firefox, then in Chrome)

**Comment by no81no** [comment]
As much as I can see you use old plugin version. This issue was fixed in the new version (long ago)

**Comment by kowalski90** [comment]
Thank you Miriam. I have updated to the newest version and is working like
it should.

I love the direction where the plugin is heading. I'll now look at any new
additions you have added as there seems to be many of them.

Best regards,
Andrei

**Comment by no81no** [comment]
Thank you,
I appreciate your feedback.
