### ISSUE TITLE
Textbox Filter Control - Problem with multi field search

### ISSUE THREAD

**Issue by tenente22** [no81no/jplist#67]
Hi,

I used PHP and MySQL with JSON and Mustache Template and I have already read the problem (similar to this -> https://github.com/no81no/jplist/issues/45 ) but I tried to replace the data-path = ".title, .desc" in "filter textbox control" to search for the title and description in a single field, but doesn't work.
Place the code here:

- jplist.php

...

	
	<script id="jplist-template" type="x-tmpl-mustache">
		{{#.}}
			<div class="list-item box-demo">	
				<div class="img left">
					<img src="{{image}}" alt="{{title}}" title="{{title}}"/>
				</div>
						
				<div class="block right">
					<p class="title">{{title}}</p>
					<p class="desc">{{description}}</p>
				</div>
			</div>
					
		{{/.}}
	</script>

...

		<div class="text-filter-box">
																	
					<i class="fa fa-search jplist-icon"></i>
   
                     			
   
  					<input 
     				 	data-path=".title, .desc" 
     				 	type="text" 
     				 	value="" 
     			       		placeholder="Search"     			   
     				 	data-control-type="textbox" 
     				 	data-control-name="desc-filter" 
     				 	data-control-action="filter"
   					/>
   					
		</div>

- but in server/controls/textbox.php , how can I add the OR in the switch of the query? 

function textbox($status){
		
		$data = $status->data;
		$result = null;
		
		if(isset($data->path) && isset($data->value) && $data->value){
		
			$result = new FilterResultModel();
			$result->param = "%$data->value%";
			
			switch($data->path){
			
				case ".title":{
					$result->query = " title like ? ";
					break;
				}
				
				case ".desc":{
					$result->query = " description like ? ";
					break;
				}
			}
		}
		
		return $result;
	}

What can I do? 
Thank you very much! 

EDIT: Bug " desc => .desc " fixed

**Comment by Deemoe** [comment]
In your data-path field you have:
<code>
data-path=".title, desc"
</code>
but shouldn't it be updated to have a . before the desc:
<code>
data-path=".title, .desc"
</code>

**Comment by tenente22** [comment]
Yep, thanks @Deemoe , I'm sorry!

I mistakenly deleted only here the "." in the class desc, but it was present in the original file.
