### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by Deemoe** [no81no/jplist#68]
Just a suggestion: Can you cross reference all the documentation on the jplist.com web site located under Home >> Products >> Controls (settings tab) to be also linked or duplicated under the Home >> Documentation section?

I had been trying in vain to find documentation about how to configure the textbox filter under Home >> Documentation, and didn't notice that there was documentation about all the settings under Home >> Products >> Controls >> Textbox Filter Control (settings tab), until I saw it linked from your answer to issue #26. 

I think other people searching for docs in the future may benefit from linking this info under Home >> Documentation.  Also, if you could have downloadable documentation which extracts all the control settings descriptions into a single document that'd be great too.  

Overall very happy with the plugin, and I like the documentation once I could find it, nice work!

**Comment by no81no** [comment]
Thank you for the great suggestion, I think it's a good idea and try to add it in the next updates.

**Comment by no81no** [comment]
Done:
https://jplist.com/documentation/controls

**Comment by Deemoe** [comment]
Looks great, I like the way you directly link to the control/settings tab, makes it super easy to navigate. Thanks!

**Comment by no81no** [comment]
Thank you for the feedback!
