### ISSUE TITLE
range-slider-toggle-filter PHP Control

### ISSUE THREAD

**Issue by shivamnetwork** [no81no/jplist#69]
Can you please help me to code range-slider-toggle-filter via PHP MYSQL

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#9

**Comment by no81no** [comment]
Added control and demo page:
https://github.com/no81no/jplist-php-mysql/blob/master/6-range-toggle-filter.html
https://github.com/no81no/jplist-php-mysql/blob/master/server/controls/range-filter.php
