### ISSUE TITLE
Listing items out of order

### ISSUE THREAD

**Issue by francjean** [no81no/jplist#70]
I'm running Google Chrome Version 40.0.2214.115 m in Windows 8 and it seems that the UL/LI Layout is listing the items out of order. I have my list set up in alphabetical order so it's pretty obvious that something has gone awry. LoL  Any assistance would be greatly appreciated.

(example: http://usaltg.com/Products/WM.html)

**Comment by no81no** [comment]
Hi,
You are using an old jPList version.
This bug was fixed long ago, please update to the latest version from github.
