### ISSUE TITLE
Multi Radio Button groups

### ISSUE THREAD

**Issue by kevinchevallier** [no81no/jplist#71]
Hey, 
i'm trying to implement two groups of radio buttons to filter my content but it doesn't play well so far. Can it be implemented?

Thanks.

**Comment by no81no** [comment]
Hi,
Please describe your use case with more details.
Also will be great to get some page / code.
Thanks

**Comment by kevinchevallier** [comment]
So, i'm trying to set up a filtering system with many inputs and i'd like to get two sets of radio buttons.
Here's the first one (works fine by itself):


`<div class="tipodebusca jplist-group cf">
	<p>Tipo de busca</p>
	<div>
		<input data-control-type="radio-buttons-filters" data-control-action="filter" data-control-name="default" data-path="default" id="default-radio" type="radio" name="jplist" checked="checked"/> 
			<label for="default-radio">todos</label>

		<input data-control-type="radio-buttons-filters" data-control-action="filter"
		data-control-name="aluguel" data-path=".aluguel" id="aluguel" type="radio" name="jplist"/> 
		<label for="aluguel">aluguel</label>

		<input data-control-type="radio-buttons-filters" data-control-action="filter"
		data-control-name="compra" data-path=".compra" id="compra" type="radio" name="jplist"/> 
		<label for="compra">compra</label>
	</div>
</div>`

And the second one:

`<div class="tipodealuguel jplist-group cf">
	<p>Tipo de aluguel</p>
	<div>
		<input data-control-type="radio-buttons-filters" data-control-action="filter" data-control-name="default2" data-path="default2" id="default-radio2" type="radio" name="jplist" checked="checked"/>
			<label for="default-radio2">todos</label>

		<input data-control-type="radio-buttons-filters" data-control-action="filter"
		data-control-name="temporada" data-path=".temporada" id="temporada" type="radio" name="jplist"/> 
		<label for="temporada-radio">temporada</label>

		<input data-control-type="radio-buttons-filters" data-control-action="filter"
		data-control-name="longoprazo" data-path=".longoprazo" id="longoprazo" type="radio" name="jplist"/> 
		<label for="longoprazo">longo prazo</label>
	</div>
</div>`

So two groups or radio with each a default.

**Comment by no81no** [comment]
There is a Radio Buttons Dropdown control for such cases:
https://jplist.com/controls/radio-buttons-dropdown
