### ISSUE TITLE
Paging show all result for data default

### ISSUE THREAD

**Issue by ProgramacionRS** [no81no/jplist#72]
<div 
				class="jplist-drop-down left" 
				data-control-type="items-per-page-drop-down" 
				data-control-name="paging" 
				data-control-action="paging"
				data-control-animate-to-top="true"
                data-control-deep-link="false">
									
				<ul>
					<li><span data-number="3"> 3 por página </span></li>
					<li><span data-number="5"> 5 por página </span></li>
					<li><span data-number="10"> 10 por página </span></li>
					<li><span data-number="all" data-default="true"> Ver todos </span></li>
				</ul>
			</div>

When I use data-default="true" in all results, don´t work, What is the solution?

**Comment by no81no** [comment]
Do you use this controls twice on the page? If so, data-default="true" should be placed in 'all results' in both controls
