### ISSUE TITLE
Pagination.php / fetchcolumn() error

### ISSUE THREAD

**Issue by asksmruti** [no81no/jplist#73]
Hi,
Today I was just trying this tool but I'm getting following error while opening "php-mysql-html.html" 
Could you please guide me to solve this issue ?

PHP Fatal error:  Call to a member function fetchColumn() on a non-object in pagination.php on line 75

====

public function getNumberOfPages(){

                        $count = 0;
                        $query = "SELECT count(ID) FROM Item ";

                        if(count($this->filter->preparedParams) > 0){
                                $query .= " " . $this->filter->filterQuery . " ";
                                $stmt = $this->db->prepare($query);
                                $stmt->execute($this->filter->preparedParams);
                                $count = $stmt->fetchColumn();
                        }
                        else{
                                $count = $this->db->query($query)->fetchColumn();
                        }

                        return $count;
                }

====

**Comment by datalynk** [comment]
Hi,

I have noticed the same...
This is a great product but debugging is prooving a little tricky...

I believe this issue is related to the PHP version???

**Comment by asksmruti** [comment]
FYI .. PHP Version is 5.4.34

**Comment by no81no** [comment]
Hi,
It  seems that $this->db->query($query) takes value of false and can't call on it fetchColumn(). Maybe there is something wrong with the sql query. Please try to run this query on mysql directly and check if it works.

**Comment by asksmruti** [comment]
Thanks no81no,  I was trying to modify the block of code (mentioned in above post) . initiated new PDO connection and get the count etc.. and it worked.. 
However while debugging I found one issue with table name in almost all select queries in different scripts. It's mentioned the table name as 'Item' where as it should be 'item' as per the provided sql schema 

Cheers!!
Smruti

**Comment by asksmruti** [comment]
TBH - Very Nice tool  no81no .. :)

**Comment by no81no** [comment]
I'm glad it works OK now. Could you please post your working code?

**Comment by asksmruti** [comment]
Hi.. I just did some dirty coding 
Created a new PDO instance inside that function.. Something like this
Ultimately the count is required 

$dbh = new PDO("mysql:host=localhost;dbname=$dbname", $dbuser, $dbpass);
                         $sql = "SELECT COUNT(ID) FROM item";
                         $stmt=$dbh->prepare($sql);
                         if (($res = $stmt->execute(array($ID))) === FALSE) {
                              echo 'Query failed!';
                              exit;
                         }
                         $count = $stmt->fetchColumn();

                        return $count;

**Comment by hossam2015** [comment]
changing the name from Item to item fixes this problem

**Comment by no81no** [comment]
The table name is moved to 'config.php' so it will be convenient to modify it:
https://github.com/no81no/jplist/tree/master/jplist-data-sources/php-mysql/server
