### ISSUE TITLE
Jplist SEO friendly

### ISSUE THREAD

**Issue by Sheilven** [no81no/jplist#74]
Hello, how can I do Jplist to be SEO friendly?

I read an article that tell me that the first step is to indicate Google that the application is indexable, to do that i have to put #! in all urls (ajax.html#!paging....)
But when i do this it doesn't filter..

Thanks!

**Comment by Sheilven** [comment]
For more information, I am using this guide  https://developers.google.com/webmasters/ajax-crawling/docs/getting-started?hl=es

**Comment by no81no** [comment]
The new property 'hashStart' is added to the options list.
You may use it like this:
$('#demo').jplist({				
	itemsBox: '.list' 
	,itemPath: '.list-item' 
	,panelPath: '.jplist-panel'	
	,deepLinking: true
	,hashStart: '#!key='
});

Please download last js version:
https://github.com/no81no/jplist/tree/master/jplist-core/minified
