### ISSUE TITLE
Reset one filter with Js/jQuery

### ISSUE THREAD

**Issue by kevinchevallier** [no81no/jplist#76]
Hi, 
is there a way to reset one filter only when an action is taken by the user (a click on a button for example)?

My case: i have a set of radio buttons (x,y,z...) and one option (x) shows up a set of buttons (a,b,c...) related to this option. I'd need to reset those buttons(a,b,c...) when the user clicks on another radio option (y,z...) not being "x".

**Comment by no81no** [comment]
Hi,
Sorry for the late response.
Unfortunately this is not supported out of the box, but it's possible to use pure jQuery to achieve it. Something like this:

$('.radio').on('change', function(){
	
	if($(this).val() !== 'x'){
		
		$('#my-btn').trigger('click');
	}
});

**Comment by kevinchevallier** [comment]
Yes that's the way i used, `.trigger`. 
Thanks.
