### ISSUE TITLE
Reset button not clear textbox value in jquery 2.1.3 (jplist jquery 2.1.3 compatibility)

### ISSUE THREAD

**Issue by jtiri** [no81no/jplist#78]
Maybe jquery 2.1.3 not fully supported in jplist, because jplist working in succesfully in demo pages jquery 1.11.1. I'am trying search and diff master and other version code, but I have not found a code that would affect the operation.

**Comment by no81no** [comment]
I've created a demo page with latest jQuery version here:
http://jsfiddle.net/8bho5vcz/9/
It seems to work OK.
Please send a link to your page so I could see the issue..
