### ISSUE TITLE
JQuery UI Range Slider Control Values don't get set. 

### ISSUE THREAD

**Issue by oztrez** [no81no/jplist#79]
I'm not skilled enough to know the correct fix but I hacked my way around it as I always set Values. At the moment the isDefault check on line 21 of range-slider-view.js is preventing Values from being set so the default for the ranges is always min-max

Trent

**Comment by no81no** [comment]
As much as I can see the control works OK here: https://jplist.com/controls/range-slider#preview
Please send a link to your page so I could see the issue (or use services like http://jsfiddle.net/).

Thanks

**Comment by oztrez** [comment]
Hi Miriam,

The control works but I'm unable to set a default. Changing the values in
the Javascript (,values: [50, 300]) should set a default on load but it
doesn't. Works with vanilla jqueryui seen here
https://jqueryui.com/slider/#range

http://jsfiddle.net/#&togetherjs=UCiwwmF6O5 . Hope that works.

Trent

**Comment by no81no** [comment]
Thank you for reporting this issue, it's fixed.
Please download the new js version:
https://github.com/no81no/jplist/tree/master/jplist-bundles-and-controls/jplist-jquery-ui-bundle/minified
