### ISSUE TITLE
Which license?

### ISSUE THREAD

**Issue by janstieler** [no81no/jplist#82]
Hi,
under which license is jplist developed?
I'm looking for an filterplugin which I can use also for themes who I will sell.

Kind regards,
Jan

**Comment by janstieler** [comment]
Hello,
now I found inside the parts that it is developed under the MIT-license.

**Comment by no81no** [comment]
Yes, all free parts are developed under the MIT license:
http://en.wikipedia.org/wiki/MIT_License
