### ISSUE TITLE
Radio Button text filter

### ISSUE THREAD

**Issue by neilp123** [no81no/jplist#83]
Hi there,

Great plugin!! 

I'm adding a new way of filtering my results. I see that you've got various types if inputs that I can use like checkboxes and toggle buttons and for each of these, you offer a data path option and a text option.
I don't want my users to be able to choose more than one option at once, so the toggle isn't really what I'm after. The radio button provides the functionality I want, but there doesn't seem to be an option to use a text field, only a data path? This is causing issues because my groups are all multi word i.e Group One, Group Two. So unless I add some custom js to strip the spaces, the data path won't work for me.

Am I missing something? Seems odd that there is no text option for the radio buttons when there is for the other inputs.

Thanks

**Comment by no81no** [comment]
Radio button text filter control is added to the toggle filters bundle:
https://raw.githubusercontent.com/no81no/jplist/master/dist/js/jplist.filter-toggle-bundle.min.js

Demo page:
https://github.com/no81no/jplist/blob/master/demo/3-radio-button-text-filters-demo.html
