### ISSUE TITLE
No results found with supplied examples and my own table

### ISSUE THREAD

**Issue by sasori7** [no81no/jplist#84]
My own mysql table wasn't working, even though I changed the fields and query to match.
So, I did an install of your PHP, MySQL and HTML sample package and ran your create.sql.
off the top, I did notice discrepancies with capitalized row names and referrals to the table in the server-html.php file.  I ran it anyway and got 'no results found'.
So, I changed the row names to lower-case, which is what the code was using.
still 'no results found'.
Lastly, I saw that your example used .desc. instead of .description. (or .Description.) so I changed the row name to desc.
still 'no results found'.
If I mess up the username in the config.php, the page just sits there with the loading animation.
Now I'm thinking I should just scrap it as maybe there is some server incompatibility (I'm on a shared godaddy account; http://www.englishsensei.com/jplist/), unless you have some other idea.  I can't figure out if I have to change any other 'setup' files other than config.php and server-html.php

**Comment by sasori7** [comment]
snippets:
CREATE TABLE `item` (
	`ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
	`Title` VARCHAR(150) NULL DEFAULT NULL,
	`Image` VARCHAR(150) NULL DEFAULT NULL,
	`Description` TEXT NULL,
	`Likes` INT(11) NULL DEFAULT NULL,
	`Keyword1` VARCHAR(50) NULL DEFAULT NULL,
	`keyword2` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)

$html .= "	<div class='block right'>";
			$html .= "		<p class='title'>" . $item['title'] . "</p>";
			$html .= "		<p class='desc'>" . $item['description'] . "</p>";
			$html .= "		<p class='like'>" . $item['likes'] . " Likes</p>";
			$html .= "		<p class='theme'>" . $item['keyword1'] . ", " . $item['keyword2'] . "</p>";

**Comment by no81no** [comment]
Hi,
Please check what errors do you get in PHP errors log now.

Thanks,

**Comment by sasori7** [comment]
Thanks for replying.
Here are the two entries (the first one occurs a few times)
PHP Warning:  Invalid argument supplied for foreach() in /home/content/30/10657930/html/content/server/domain/action.php on line 23
PHP Fatal error:  Call to a member function fetchColumn() on a non-object in /home/content/30/10657930/html/content/server/domain/pagination.php on line 75
PHP Warning:  Invalid argument supplied for foreach() in /home/content/30/10657930/html/jplist/server/domain/action.php on line 23

this comes from:
http://www.englishsensei.com/list01.html

Your sample page is at:
http://www.englishsensei.com/jplist/
the 'line 23' error is generated here, as well.

**Comment by sasori7** [comment]
I was thinking of using the older method of querying the data from mysql instead of PDO as maybe the query itself isn't working.
Also, when looking at the code, I don't really see the connection between the query in domain/server.php.

**Comment by no81no** [comment]
Sorry for the late response.
Please check DB_TABLE variable in config.php file. It should contain your table name (item).

**Comment by no81no** [comment]
Also all other fields should contain proper values (DB_NAME, DB_USER, DB_PASSWORD, DB_HOST).

**Comment by no81no** [comment]
I've just started from scratch and created a new mysql db.
I used 'create.sql' to create a table and fill it with the data, and configured the server/config.php file.
The following value was wrong:
define('DB_TABLE', 'item2');
I replaced it to:
define('DB_TABLE', 'item');

After that all worked fine. 
Do you still have errors or maybe you found a solution?

**Comment by cgo72123** [comment]
I have this same exact issue, and nope that doesn't solve it.

**Comment by cgo72123** [comment]
Upgrading to php 5.4 fixed it for me

**Comment by no81no** [comment]
Thank you for the update.

**Comment by sasori7** [comment]
I'll try that, I've moved on from the script, for now, but I'll check.

**Comment by no81no** [comment]
Thank you, please let me know if it will work for you.

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#7
