### ISSUE TITLE
Filtering is clunky on keyUp

### ISSUE THREAD

**Issue by datalynk** [no81no/jplist#85]
Having problems with the search filter box. As you type it feels very clunky with the keyUp functionality and is deleting characters as you type.

**Comment by datalynk** [comment]
To see what I mean, please goto http://siddhi.usvolleyballinstitute.com/index.php?option=com_usg_programs&view=programs&Itemid=102 and enter "Soccer" or "Golf" or "Basketball" into the text box above the search results.

**Comment by sasori7** [comment]
just offhand, it looks like that box is within the div being targeted for updating.  If you pull the box out of div id=demo, it might stop.

where are you pulling your data?

**Comment by datalynk** [comment]
Hi sasori7, worth a try... I moved the text box and the Pagination totals out of the id=demo div (placed just above) however in this position it has no effect at all. It looks like all controls MUST be in the demo div.

You can view the revised code here...
http://everest.usvolleyballinstitute.com/index.php?option=com_usg_programs&view=programs&Itemid=102

**Comment by no81no** [comment]
I see that you're using a server side version of jPList. In this case it's better to use text filter with button instead of keyup. Please check usage example here:
https://jplist.com/controls/textbox-filter#usage

**Comment by datalynk** [comment]
Hi no81no, in this case jplist will be of no use as the keyup filtering is a requirement of the project, and we will always be connecting to an API that serves large datasets. I also bought the Bootstrap plugins, so unless this can work as expected can I get a refund?

**Comment by no81no** [comment]
Sure, no problem. You can send me paypal transaction id to no81no@gmail.com
