### ISSUE TITLE
no results

### ISSUE THREAD

**Issue by Mirabelle13** [no81no/jplist#87]
Hi :),
I watched all issues but I dont'manage to understand why I have "no results".
This is my url : http://www.mirabellegallego.com/content/php-mysql-html.html

Have you need others elements to help me ?

Thanks a lot,

Mirabelle

**Comment by sasori7** [comment]
same here.
I posted the same issue a few days ago.
Now, I'm thinking that I should switch the query code to 'traditional' code.

**Comment by no81no** [comment]
Hi,
Please check what errors do you get in PHP errors log.

Thanks,

**Comment by Mirabelle13** [comment]
Hi,
Thanks for you answer, but I'm beginer in PHP (in english also sorry) howI I see the errors in PHP errors log ? with Firebug ? with a script ?

Thanks a lot,

Mirabelle

**Comment by sasori7** [comment]
you have to turn on error logging in the php.ini file.  You should contact your hosting company for help.  Googling this phrase will show you how to do it.

**Comment by no81no** [comment]
Sorry for the late response. Could you please check config.php file that contained in server folder? It should contain proper values that you can get from your hosting provider.

DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, TABLE  - connection string to your database and table.

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#8
