### ISSUE TITLE
Search filter not searching exact phrases (from beginning)

### ISSUE THREAD

**Issue by dejmzh** [no81no/jplist#89]
Hello,

I expected the search filter plugin to search for the EXACT phrase (from beginning) but I realized that it doesn't work as I expected.

I need to sort my list of results by only the first letter (text) because I'd like to get some kind of glossary working.

Is there any option / quick fix to get this working?

Thanks in advance
Jonas

**Comment by no81no** [comment]
Hello,
This feature was added recently as **data-mode="startsWith"** attribute:
https://jplist.com/controls/textbox-filter#settings

Thanks,
