### ISSUE TITLE
'no results' on brand new install of php-mysql-data-source.zip

### ISSUE THREAD

**Issue by sasori7** [no81no/jplist#90]
Installed exactly as laid out in the zip and set up the table from the supplied sql file and set up the config.php in the server folder; nothing else changed.

http://reliabuy.com/list/php-mysql-html.html

**Comment by no81no** [comment]
Please check server/config.php.
Does it contain proper values?
DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, TABLE  are connection string to your database and table.

**Comment by sasori7** [comment]
In the setup.php file included in the zip, there is DB_TABLE, not TABLE.
Which one is correct?

**Comment by sasori7** [comment]
I tested it with TABLE and still no result.  The DB_ setting on this test location are exactly as they are on the functioning site using the same database; they work.

**Comment by sasori7** [comment]
I noticed, again, that the table's names created by the provided create.sql are capitalized, whereas the query inside config.php are not.  Additionally, I confirmed the query was not working with phpmyadmin.
I changed it to match the case in the table, but still got no result:
original:
$query = "SELECT title, description, image, likes, keyword1, keyword2 FROM item";
changed:
$query = "SELECT Title, Description, Image, Likes, Keyword1, keyword2 FROM item";

**Comment by no81no** [comment]
How about to make a skype session to find out the issue? It looks like configuration problem..

**Comment by sasori7** [comment]
We can give that a shot.  However, I've gotten the same results installing on two different completely servers running LAMP.
Has anyone simply changed the config.php file, run the sql file and been up and running on a linux box with the php-mysql-data-source.zip?
Also, I'm curious which server setup ignores Case:
$query = "SELECT title, description, image, likes, keyword1, keyword2 FROM item";
CREATE TABLE `item` (
	`ID` MEDIUMINT NOT NULL AUTO_INCREMENT,
	`Title` VARCHAR(150) NULL DEFAULT NULL,
	`Image` VARCHAR(150) NULL DEFAULT NULL,
	`Description` TEXT NULL,
	`Likes` INT(11) NULL DEFAULT NULL,
	`Keyword1` VARCHAR(50) NULL DEFAULT NULL,
	`keyword2` VARCHAR(50) NULL DEFAULT NULL,
	PRIMARY KEY (`ID`)
)
An NT box, perhaps?
My suggestion is that there is something a bit deeper, that is still amiss.

**Comment by no81no** [comment]
I use it on windows, so maybe it's a LAMP case issue.
I tested it again on my comp:
- I've just started from scratch and created a new mysql db (and I'm using apache server).
- I used 'create.sql' to create a table and fill it with the data, and configured the server/config.php file.
- The following value was wrong:
define('DB_TABLE', 'item2');
I replaced it to:
define('DB_TABLE', 'item');

After that all worked fine.

Please let me know if you've found a solution for your LAMP environment?

**Comment by no81no** [comment]
This issue was moved to no81no/jplist-php-mysql#3
