### ISSUE TITLE
Localstorage pb

### ISSUE THREAD

**Issue by drpark** [no81no/jplist#92]
Hello,
i've got some sliders and a select but the storage does not work.
Is the storage limited only to text elements?
The website is not yet online but you can see the code here
http://dev4.double-y.fr/poeles-a-pellets/

Thank's in advance

**Comment by no81no** [comment]
Hello,
I checked that localstorage locally for range slider, sort control and checkboxes control, and found that it works well. So we could check 2 scenarios:
1. It could be not the latest version. If so, please try download the latest one from github.
2. Other scripts may have conflicts with jplist. It's possible  to create a test page without other plugins and this way to check if it's the case.
Please let me know if it helps.

**Comment by drpark** [comment]
thank no81no it was a conflict with this old protoaculous.
all work fine now.
Thank you!

**Comment by no81no** [comment]
I'm glad that it works for you now!
