### ISSUE TITLE
Pagination in Table Bootstrap

### ISSUE THREAD

**Issue by Maxchip** [no81no/jplist#93]
Hello Miriam Zusin,

Congratulations for excellent work.
jPList is the best. It’s simplicity.
I’m very happy find the jPList.
I was searching it long  time.

I’m beginner in jQuery and I want learn more.

But I need your help.
Is possible create Pagination in Table Bootstrap?
Can you see my project?

Thanks

Cezar

![image](https://cloud.githubusercontent.com/assets/11981239/7683823/05054bdc-fd58-11e4-8747-1a97eb639aa9.png)

![image](https://cloud.githubusercontent.com/assets/11981239/7683872/54a220de-fd58-11e4-926b-6936a2b26a1b.png)

![image](https://cloud.githubusercontent.com/assets/11981239/7683837/1b69b11a-fd58-11e4-9d6f-813023f62e01.png)

![image](https://cloud.githubusercontent.com/assets/11981239/7683848/30f84c30-fd58-11e4-9541-ccb8510e515e.png)

**Comment by no81no** [comment]
Hi Cezar,
I appreciate your feedback. 
It's possible to paginate any table.

Please check the following options:
- Pagination Bundle (free), https://jplist.com/bundles/free-pagination-bundle
- Bootstrap Pagination Bundle (paid), https://jplist.com/bundles/bootstrap-pagination

Thanks,
Miriam

**Comment by Maxchip** [comment]
Hi Miriam,
Thanks for reply.
I already buy your Bootstrap Pagination Bundle yesterday.
I don't see sample with tag "table", just "div".
I need more help.
My project is very simple, just a query. Asp.Net/C#/MS-SQL/Jquery/BootStrap.
I want implement pagination, sort and filter by fields (TextBox/DropDown/Date/CheckBox). 
Are you accept help me with my project?
I can pay for this help or make a donation for you.
Let me know.
Thanks
Cezar

**Comment by no81no** [comment]
Hi Cezar,
Please send me details of your project to no81no@gmail.com

Thanks
