### ISSUE TITLE
reset sliders

### ISSUE THREAD

**Issue by renanal** [no81no/jplist#94]
Hi
I'm  trying to reset by control  jplist-reset-btn" data-control-type="reset" data-control-name="reset" data-control-action="reset" 
but it do not reset sliders  only checkbox and sorting.
Thanks a lot
Renana

**Comment by renanal** [comment]
Hi
When I'm changing sorting combo the paging is not going to the first page he stay on the page that i was before.
Thanks
Renana

**Comment by no81no** [comment]
Please use data-jump-to-start="true" attribute in the pagination control.
You can see all the options here: https://jplist.com/controls/pagination#settings

Thanks

**Comment by no81no** [comment]
Reopened

**Comment by renanal** [comment]
Thank A Lot




[cid:admailBnr10.jpg]<http://deals.arkia.co.il/msite/new_site/Opera_Masada_2/index.html?utm_source=admail&utm_medium=banner&utm_campaign=admail_banner>
________________________________

powered by admail<http://www.admail.us>

**Comment by renanal** [comment]
Can you help me with the first question please

"I'm trying to reset by control jplist-reset-btn" data-control-type="reset" data-control-name="reset" data-control-action="reset"
but it do not reset sliders only checkbox and sorting."






[cid:admailBnr10.jpg]<http://deals.arkia.co.il/msite/new_site/Opera_Masada_2/index.html?utm_source=admail&utm_medium=banner&utm_campaign=admail_banner>
________________________________

powered by admail<http://www.admail.us>

**Comment by renanal** [comment]
Another question please,
I'm using paging  at my top page an at the bottom of my page.
When I'm in the bottom,and press on the first page the page staying in bottom an not going up to the start of the page,
Thanks again for your help

**Comment by renanal** [comment]
Hi
I found it it's
data-control-animate-to-top="true"
Thanks

**Comment by pepesenaris** [comment]
I have a similar issue.... i would like to programmatically reset the min and max value in a range-toogle filter.... is there a way to do it?

I tried with changing the data-min value using attr but is does not work

**Comment by no81no** [comment]
The issue with reset button is fixed. Please download the latest js:
https://github.com/no81no/jplist/blob/master/jplist-bundles-and-controls/jplist-jquery-ui-bundle/minified/jplist.jquery-ui-bundle.min.js

To reset it programmatically you may use a hidden reset button and trigger it like this:

```js
$('[data-control-type="reset"]').trigger('click')
```

**Comment by renanal** [comment]
Miriam
Thanks a lot, It's working!!
Regards
Renana





Renana Rozen
Project Manager
renanal@arkia.co.il<mailto:renanal@arkia.co.il> | M:
T: 972-3-6903705 | F: 972-3-6900828
[http://i1262.photobucket.com/albums/ii612/Admail/5_zpsdcfksqb9.jpg]<http://www.arkia.co.il/>

[http://i1262.photobucket.com/albums/ii612/Admail/Facebook_zpsaqfdkqo1.png]<https://www.facebook.com/ArkiaAirlines> [http://i1262.photobucket.com/albums/ii612/Admail/YouTube_zpsnwe7qlj9.png] <https://www.youtube.com/user/TravelArkia>  [http://i1262.photobucket.com/albums/ii612/Admail/Instagram_zpsiggxqtqm.png] <https://instagram.com/arkia_airlines/>  [http://i1262.photobucket.com/albums/ii612/Admail/Twitter_zpsuq80pmas.png] <https://twitter.com/TravelArkia>  [http://i1262.photobucket.com/albums/ii612/Admail/Google_zpsvi1afzor.png] <https://plus.google.com/111191545491734665050/posts>  [http://i1262.photobucket.com/albums/ii612/Admail/Home_zpss233z7xh.png] <http://www.arkia.co.il/>


[cid:admailBnr19.jpg]<http://www.arkia.co.il/deals/fattal-d2?utm_source=arkia_admail&utm_medium=banner&utm_campaign=ad_mail_fattal>
________________________________

powered by admail<http://www.admail.us>

**Comment by no81no** [comment]
You're welcome :)
