### ISSUE TITLE
Sorting by two values

### ISSUE THREAD

**Issue by renanal** [no81no/jplist#95]
Hi
It is Possible to sort by tow values in the same sort, Secondary sort.
example:  order by price,date

Thanks

**Comment by no81no** [comment]
Hi,
It's possible using 2 dropdown controls like here:
https://jplist.com/controlsexamples/double-sort

Thanks

**Comment by renanal** [comment]
Thanks for your reply
But I mean in the same sort I  want to sort first by price and second by name for example, I mean secondary sort.




[cid:admailBnr10.jpg]<http://deals.arkia.co.il/msite/new_site/Opera_Masada_2/index.html?utm_source=admail&utm_medium=banner&utm_campaign=admail_banner>
________________________________

powered by admail<http://www.admail.us>

**Comment by no81no** [comment]
Unfortunately it's not supported for now.

**Comment by renanal** [comment]
Thanks for your reply





[cid:admailBnr10.jpg]<http://deals.arkia.co.il/msite/new_site/Opera_Masada_2/index.html?utm_source=admail&utm_medium=banner&utm_campaign=admail_banner>
________________________________

powered by admail<http://www.admail.us>

**Comment by no81no** [comment]
Done using multiple data attributes:
http://localhost:8080/documentation/control-settings/sort-dropdown-control
http://jplist.com/documentation/control-settings/sort-dropdown-select-control
