### ISSUE TITLE
jplist-ios-button

### ISSUE THREAD

**Issue by MWTAD** [no81no/jplist#97]
Is it possible to set the default for the "jplist-ios-button" on open (instead closed) for all formats?
Or even better: disable it? If yes, how can I do this?

I use the pagination control only and I want to see it on the screen all the time.

**Comment by no81no** [comment]
You can change it using CSS like this:

@media only screen and (max-width: 600px){

/* hide ios button */
.jplist-ios-button{
   display: none;
}

/* show the panel */
.jplist-panel{
   display: block;
}
}

**Comment by MWTAD** [comment]
Great,
Thank you very much!

Date: Tue, 26 May 2015 03:45:30 -0700

**Comment by no81no** [comment]
You're welcome :)
