### ISSUE TITLE
insert advertissement inside the result

### ISSUE THREAD

**Issue by thibaultvanc** [no81no/jplist#98]
Hello, 
wonderful plugin
I wanted to know if there is a possibilitie to insert avertissement inside the result ?

Thank you

**Comment by no81no** [comment]
Hello,
You have full control on HTML and may insert any content before calling jPList.
In case of dynamic content you may use 'Redraw Callback' function that occurs on every jplist action like sort, filter, pagination etc.
https://jplist.com/documentation/js-settings#redraw-callback-function

Thanks,

**Comment by thibaultvanc** [comment]
thanks for your answer
