### ISSUE TITLE
filter buttons in the sidebar

### ISSUE THREAD

**Issue by thibaultvanc** [no81no/jplist#99]
Hello,
Is it possible to put the filtering action in the sidebar. 

The filter buttons would be outside the main div. see the picture below.
Is it possible ? 

it would be perfect to keep the top panel AND the left !

Thanks You
![image](https://cloud.githubusercontent.com/assets/10731886/7988339/3091bdb0-0ae3-11e5-8ff4-88b56c07dfd6.png)

**Comment by no81no** [comment]
You can try something like this:

$('document').ready(function(){

   //the script runs on the whole BODY of HTML (or some general DIV wrapper)
   $('body').jplist({				
      itemsBox: '.list' 
      ,itemPath: '.list-item' 
      ,panelPath: '.jplist-panel'	
   });
   
});

<body>
   
    <div class="left-panel jplist-panel">....</div>

   
    <div class="main-panel jplist-panel">....</div>

  ...
</body>

**Comment by thibaultvanc** [comment]
yesssss
!!!
;)
